{% set name = "pycocotools" %}
{% set version = "2.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cbb8c2fbab80450a67ee9879c63b0bc8a69e58dd9a0153d55de404c0d383a94b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - pip
    - python
    - cython >=0.27.3
    - matplotlib >=2.1.0
  run:
    - python
    - cython >=0.27.3
    - matplotlib >=2.1.0

test:
  imports:
    - pycocotools

about:
  home: https://github.com/cocodataset/cocoapi
  license: BSD
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/license.txt'
  summary: Tools for working with the MSCOCO dataset
