package:
  name: r-rmutil
  version: "1.1.0"

source:
  fn: rmutil_1.1.0.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rmutil_1.1.0.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rmutil/rmutil_1.1.0.tar.gz

build:
  number: 0
  skip: True # [osx]
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r >=1.4
    - gcc # [linux]
    - llvm # [osx]

  run:
    - r >=1.4
    - libgcc # [linux]

test:
  commands:
    - $R -e "library('rmutil')"

about:
  home: https://cran.r-project.org/web/packages/rmutil/index.html
  license: GPL-2
  summary: A toolkit of functions for nonlinear regression and repeated measurements not to be used by itself but called by other Lindsey packages.
  license_family: GPL2
