{% set name = "SSS-test" %}
{% set version = "2020.01.13" %}
{% set revision = "e53c7200488b323980a2f9b46c69fe96236427c5" %}
{% set sha256 = "835fffa4713ddb85fa2e244b5345a4f04034a6154e6fe33249d1eff3697ac722" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/waltercostamb/{{ name }}/archive/{{ revision }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - perl.patch
    - bash.patch

build:
  noarch: generic
  number: 0

requirements:
  host:
    - viennarna
  run:
    - perl-bioperl
    - rnasnp
    - muscle
    - viennarna
    - perl-fast
    - perl-statistics-r
 
test:
  commands:
    - local.sh | grep "Usage"
    - SSS.sh | grep "Usage"

about:
  home: https://github.com/waltercostamb/SSS-test
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: "Selection on the Secondary Structure-test: a test that detects positive and negative selection from a set of orthologs, either small or long ncRNAs."

extra:
  identifiers:
    - doi:10.1186/s12859-019-2711-y
