package:
  name: jvarkit-sam2tsv
  version: "1.0"

source:
  fn: 20170920_master.tar.gz
  url: https://github.com/lindenb/jvarkit/archive/20170920_master.tar.gz
  md5: 9801d53e5f03079e8b5fcdaf7e0f3c9f

build:
  number: 0

requirements:
  build:
    - openjdk >=8
    - cmake
   
  run:
    - openjdk >=8

test:
  commands:
    - sam2tsv -h

about:
  home: http://lindenb.github.io/jvarkit/Sam2Tsv.html
  license: MIT
  summary: Prints the SAM alignments as a TAB delimited file.
