{% set name="jupyter-duoauthenticator" %}
{% set version="2019.02.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/unlhcc/{{ name }}.git
  git_tag: 683c77b0b9e8b65e09d7a26ec357b4aa4a36d9cf

build:
  number: 0
  skip: True  # [py27 or osx]
  script: "{{ PYTHON }} -m pip install . --no-deps -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - tornado
    - jupyterhub
    - duo_python

test:
  imports:
    - duoauthenticator

about:
  home: https://github.com/unlhcc/jupyter-duoauthenticator
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Simple Duo Authenticator Plugin for JupyterHub.

extra:
  skip-lints:
    - uses_git_url
    - missing_hash
