{% set name = "sumo" %}
{% set version = "1.2.0" %}
{% set sha256 = "6949702ec5932852e5cc9dc02d099c9fa406feac960cff01936c9d5948428b21" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - sumo-bandplot = sumo.cli.bandplot:main
    - sumo-bandstats = sumo.cli.bandstats:main
    - sumo-dosplot = sumo.cli.dosplot:main
    - sumo-kgen = sumo.cli.kgen:main
    - sumo-phonon-bandplot = sumo.cli.phonon_bandplot:main
    - sumo-optplot = sumo.cli.optplot:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - h5py
    - matplotlib
    - numpy
    - phonopy >=2.1.3
    - pymatgen >=2017.12.30
    - scipy
    - seekpath
    - spglib

test:
  imports:
    - sumo
    - sumo.cli
    - sumo.electronic_structure
    - sumo.io
    - sumo.phonon
    - sumo.plotting
    - sumo.symmetry
  commands:
    - sumo-bandplot --help
    - sumo-bandstats --help
    - sumo-dosplot --help
    - sumo-kgen --help
    - sumo-phonon-bandplot --help
    - sumo-optplot --help

about:
  home: https://github.com/smtg-ucl/sumo
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: "Heavy weight plotting tools for ab initio solid-state calculations."
