package:
  name: qiime
  version: !!str 1.8.0

source:
  fn: qiime-1.8.0.tar.gz
  url: https://pypi.python.org/packages/source/q/qiime/qiime-1.8.0.tar.gz
  md5: 55bca3624114e81d33a2c2382bfb5266
  patches:
    - Fix-Python-version-parsing.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - qiime = qiime:main
    #
    # Would create an entry point called qiime that calls qiime.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python ==2.7.3
    - numpy >=1.5.1,<=1.7.1
    - matplotlib >=1.1.0,<=1.3.1
    - cogent ==1.5.3
    - pynast ==1.2.2
    - qcli
    - gdata
    - biom-format ==1.3.1
    - emperor >=0.9.3

  run:
    - python ==2.7.3
    - numpy >=1.5.1,<=1.7.1
    - matplotlib >=1.1.0,<=1.3.1
    - cogent ==1.5.3
    - pynast ==1.2.2
    - qcli
    - gdata
    - biom-format ==1.3.1
    - emperor >=0.9.3
    - pyqi

test:
  # Python imports
  imports:
    - qiime
    - qiime.denoiser
    - qiime.parallel
    - qiime.pycogent_backports
    - qiime.workflow
    - qiime_test_data

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.qiime.org
  license: GPL
  summary: 'Quantitative Insights Into Microbial Ecology'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
