package:
  name: ghc
  version: 8.2.2

source:
  fn: ghc-8.2.2-x86_64-unknown-linux.tar.bz2 # [linux64]
  url: https://downloads.haskell.org/~ghc/8.2.2/ghc-8.2.2-x86_64-centos67-linux.tar.xz # [linux64]
  sha1: d66dc65a8e3b534ae319ba791e77c4fec5bc1fae # [linux64]
  patches:
    - ldflags.patch

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - gmp 4.3*
    - readline 5.2*
    - ncurses 5.9*
    - perl

  run:
    - gmp 4.3*
    - readline 5.2*
    - ncurses 5.9*
    - perl

test:
  commands:
    - ghc --help

about:
  home: https://www.haskell.org/ghc/
  license: BSD
  summary: "GHC is a state-of-the-art, open source, compiler and interactive environment for the functional language Haskell."
