package:
  name: quasr
  version: "v6.09"

source:
  fn: master.zip
  url: https://github.com/simonjwatson/QUASR/archive/master.zip
  md5: 437508e4c1c5cabe69798494349fb416
  patches:
    - paths.patch

build:
  number: 0
  skip: True # [py27]
  skip: True # [osx]

requirements:
  build:
    - python
    - r
    - samtools

  run:
    - python
    - r
    - samtools

test:
  commands:
    - readset_parser.py --help
    - quality_control.py --help
    - pileup_consensus.py --help
    - pileup_depth_graph.py --help
    - pileup_minority_graph.py --help
    - pileup_minority_list.py --help
    - pileup_minority_numbers.py --help
    - fastq_duplicate_remover.py --help
    - fastq_remove_Ns.py --help
    - convert_sam_to_pileup.sh -h 2>&1 | grep convert_sam_to_pileup > /dev/null 

about:
  home: "https://github.com/simonjwatson/QUASR"
  license: GNU GPL
  summary: "QUASR is lightweight pipeline for processing and analysis of high-throughput sequencing data."
