package:
  name: r-rook
  version: "1.1_1"

source:
  fn: Rook_1.1-1.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/Rook_1.1-1.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/Rook/Rook_1.1-1.tar.gz

build:
  number: 0
  skip: True # [osx]
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r
    - r-brew
    - gcc

  run:
    - r
    - r-brew
    - libgcc

test:
  commands:
    - $R -e "library('Rook')"

about:
  #home:
  license: GPL-2
  summary: This package contains the Rook specification and convenience software for building
    and running Rook applications. To get started, be sure and read the 'Rook' help
    file first.
  license_family: GPL2
