package:
  name: r-visnetwork
  version: "1.0.3"

source:
  fn: visNetwork_1.0.3.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/visNetwork_1.0.3.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/visNetwork/visNetwork_1.0.3.tar.gz

build:
  number: 0
  skip: True # [osx]
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r
    - r-htmltools
    - r-htmlwidgets
    - r-jsonlite
    - r-magrittr

  run:
    - r
    - r-htmltools
    - r-htmlwidgets
    - r-jsonlite
    - r-magrittr

test:
  commands:
    - $R -e "library('visNetwork')"

about:
  home: https://github.com/datastorm-open/visNetwork
  license: MIT + file LICENSE
  summary: Provides an R interface to the 'vis.js' JavaScript charting library. It allows an
    interactive visualization of networks.
  license_family: MIT
