mpi:
  - mpich

pin_run_as_build:
  mpich: x.x
  openmpi: x.x
  hypre:
    max_pin: x.x
  metis:
    max_pin: x.x
  parmetis:
    max_pin: x.x
  ptscotch:
    max_pin: x.x
  scalapack:
    max_pin: x.x
  mumps-mpi:
    max_pin: x.x
  suitesparse:
    max_pin: x.x  # [not osx]
    max_pin: x.x.x  # [osx]
