{% set name = "fbpca" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 150677642479663f317fdbb5e06dab3f98721cf7031bb4a84113d7a631c472d1

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy >=1.9
    - scipy >=0.14
    
test:
  imports:
    - fbpca

about:
  home: https://www.facebook.com
  license: BSD
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Fast computations of PCA/SVD/eigendecompositions via randomized methods.
  dev_url: https://github.com/facebook/fbpca