package:
  name: muscle [linux64]
  version: 3.8.31

source:
  fn: muscle3.8.31_i86linux64.tar.gz
  url: http://www.drive5.com/muscle/downloads3.8.31/muscle3.8.31_i86linux64.tar.gz
  md5: 97d2f9bb25e30ed62a6e132d644ed700

build:
  number: 0

test:
  commands:
     - muscle3.8.31_i86linux64 -version

about:
  home: http://drive5.com/muscle
  license: LGPL

# vim:set ts=8 sw=2 
