{% set name = "mumax3" %}
{% set version = "3.10.2ae87b9" %}
{% set sha256 = "e0eb381902264fd04013ea17220d81705dc650486592d1ef7f66cc0472f36f55" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mumax/3/archive/2ae87b9.zip
  sha256:  {{ sha256 }}
  folder: src/github.com/mumax/3

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - cuda_driver
    - go-cgo
  host:
    - cudatoolkit
  run:
    - cudatoolkit
    - gnuplot

test:
  commands:
    - mumax3 -h 2>&1 | grep mumax3 > /dev/null
  requires:
    - cuda_driver

about:
  home: http://mumax.github.io
  license: GPLv3
  license_family: GPL
  license_file: src/github.com/mumax/3/LICENSE
  summary: "GPU-accelerated micromagnetic simulator"
