package:
  name: libtheora
  version: 1.1.1

source:
  fn: libtheora-1.1.1.tar.bz2
  url: http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2
  md5: 292ab65cedd5021d6b7ddd117e07cd8e
	
build:
    number: 0
    skip: True # [osx]

requirements:
  build:
    - gcc
    - libogg
    - libvorbis
    - libpng <1.6
    - zlib

  run:
    - libgcc
    - libogg

test:
  commands:
    - test -f ${PREFIX}/lib/libtheora.so
    - test -f ${PREFIX}/lib/libtheoradec.so
    - test -f ${PREFIX}/lib/libtheoraenc.so
    - test -f ${PREFIX}/lib/libtheora.a
    - test -f ${PREFIX}/lib/libtheoradec.a
    - test -f ${PREFIX}/lib/libtheoraenc.a

about:
  home: https://theora.org
  license: BSD
  summary: "Theora is a free and open video compression format from the Xiph.org Foundation."
