package:
  name: r-zerone
  version: "1.0"

source:
  fn: master.zip
  url: https://github.com/nanakiksc/zerone/archive/master.zip
  md5: a308de146964d1b06ae74b6d9a1297dc

build:
  number: 0
  skip: True # [osx]

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r
    - gcc
    - gmp {{CONDA_GMP}}*
  run:
    - r
    - libgcc
    - gmp {{CONDA_GMP}}*

test:
  commands:
    - $R -e "library('zerone')"

about:
  home: "https://github.com/nanakiksc/zerone"
  license: GPLv3
  license_file: LICENSE.md
  summary: "Zerone discretizes several ChIP-seq replicates simultaneously and resolves conflicts between them. After the job is done, Zerone checks the results and tells you whether it passes the quality control."
