{% set name = "imlib2" %}
{% set version = "1.6.1" %}
{% set sha256 = "668696d0a8961bb57353fe96669f44bbdf1696221a65da563408a5010c5bd735" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://downloads.sourceforge.net/project/enlightenment/imlib2-src/{{ version }}/imlib2-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config # [osx]
  host:
    - jpeg
    - libpng
    - freetype
    - zlib
    - bzip2
    - libtiff
    - giflib
    - libwebp
    - xorg-libx11
    - xorg-libxext
  run:
    - jpeg
    - libpng
    - freetype
    - zlib
    - bzip2
    - libtiff
    - giflib
    - libwebp
    - xorg-libx11
    - xorg-libxext

test:
  commands:
    - imlib2-config --version

about:
  home: https://docs.enlightenment.org/api/imlib2/html/index.html
  license: Custom OSS
  license_family: OTHER
  license_file: COPYING
  summary: "Imlib 2 is the successor to Imlib. It is NOT a newer version - it is a completely new library."
