package:
  name: macs2
  version: "2.1.0.20150731"

source:
  fn: MACS2-2.1.0.20150731.tar.gz
  url: https://pypi.python.org/packages/source/M/MACS2/MACS2-2.1.0.20150731.tar.gz
  md5: 026a210b967e28e10e220d61744c82f0
  patches:
   # Patch to change compile flag -Ofast to -O3 for pre-4.6 GCC versions
   - gcc44_flags.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - macs2 = macs2:main
    #
    # Would create an entry point called macs2 that calls macs2.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.6

  run:
    - python
    - numpy >=1.6

test:
  # Python imports
  imports:
    - MACS2
    - MACS2.IO

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/taoliu/MACS/
  license: BSD License
  summary: 'Model Based Analysis for ChIP-Seq data'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
