{% set name = "bwapy" %}
{% set version = "0.1.3" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: https://github.com/nanoporetech/{{ name|lower }}.git
  git_rev: 7c6c2d7

build:
  number: 0
  skip: True # [py2k]

requirements:
  build:
    - python
    - cffi
    - gcc # [not osx]
    - llvm # [osx]
    - pytz
    - python-dateutil
  run:
    - python
    - cffi
    - libgcc # [not osx]
    - pytz
    - python-dateutil

test:
  commands:
    - python -c "from bwapy import BwaAligner"

about:
  home: https://github.com/nanoporetech/bwapy/
  license: MIT
  license_family: Other
  license_file: ''
  summary: bwapy
  description: 'bwapy - Python bindings to bwa mem'
  doc_url: 'https://nanoporetech.github.io/bwapy/'
