variables:
  BIOCONDA_UTILS_TAG: "gitlabci-master"
  BIOCONDA_UTILS_ARGS: "--loglevel=info"
  MINICONDA_VER: "4.2.12"
  SUBDAGS: "1"
  SUBDAG: "0"

stages:
  - build
  - deploy

build:
  stage: build
  image: unlhcc/docker-glibc
  except:
    - master
  tags:
    - docker
  before_script:
    - scripts/gitlabci-setup.sh
  script:
    - scripts/gitlabci-run.sh

deploy:
  stage: deploy
  image: unlhcc/docker-glibc
  only:
    - master
  tags:
    - docker
  before_script:
    - scripts/gitlabci-setup.sh
  script:
    - scripts/gitlabci-run.sh
