variables:
  BIOCONDA_UTILS_TAG: "gitlabci-master"
  BIOCONDA_UTILS_BUILD_ARGS: "--loglevel=info"
  MINICONDA_VER: "4.3.21"
  SUBDAGS: "1"
  SUBDAG: "0"

stages:
  - build
  - deploy
  - sync-to-github

build-linux:
  stage: build
  image: unlhcc/docker-glibc
  except:
    - master
  tags:
    - docker
  before_script:
    - export ANACONDA_PREFIX=/anaconda
    - scripts/gitlabci-setup.sh
  script:
    - scripts/gitlabci-run.sh

build-osx:
  stage: build
  except:
    - master
  tags:
    - osx
  before_script:
    - export ANACONDA_PREFIX=`mktemp -d`/anaconda
    - export CONDARC=$ANACONDA_PREFIX/.condarc && rm -rf ~/.condarc
    - scripts/gitlabci-setup.sh
  script:
    - scripts/gitlabci-run.sh
    - rm -rf $ANACONDA_PREFIX

deploy-linux:
  stage: deploy
  image: unlhcc/docker-glibc
  only:
    - master
  tags:
    - docker
  before_script:
    - export ANACONDA_PREFIX=/anaconda
    - scripts/gitlabci-setup.sh
  script:
    - scripts/gitlabci-run.sh

deploy-osx:
  stage: deploy
  only:
    - master
  tags:
    - osx
  before_script:
    - export ANACONDA_PREFIX=`mktemp -d`/anaconda
    - export CONDARC=$ANACONDA_PREFIX/.condarc && rm -rf ~/.condarc
    - scripts/gitlabci-setup.sh
  script:
    - scripts/gitlabci-run.sh
    - rm -rf $ANACONDA_PREFIX

sync-to-github:
  stage: sync-to-github
  image: unlhcc/crane-build-el6
  allow_failure: yes
  only:
    - master
  script:
    - eval $(ssh-agent -s) > /dev/null
    - mkdir -p ~/.ssh
    - chown 700 ~/.ssh
    - echo $SSH_KNOWN_HOSTS > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-add <(echo "$GITHUB_SSH_DEPLOY_PKEY" | base64 --decode)
    - git config user.name "HCC Gitlab CI"
    - git config user.email "hcc-support@unl.edu"
    - git checkout master
    - git remote add github git@github.com:unlhcc/hcc-conda-recipes.git
    - git push github +master
