package:
  name: libopus
  version: 1.1.2

source:
  fn: opus-1.1.2.tar.gz
  url: http://downloads.xiph.org/releases/opus/opus-1.1.2.tar.gz
  md5: 1f08a661bc72930187893a07f3741a91
	
build:
    number: 0
	  
requirements:
  build:
    - gcc
  run:
    - libgcc

test:
  commands:
    - test -f ${PREFIX}/lib/libopus.so
    - test -f ${PREFIX}/lib/libopus.a
    - test -d ${PREFIX}/include/opus

about:
  home: https://www.opus-codec.org/
  license: BSD
  summary: "Opus is a codec for interactive speech and audio transmission over the Internet."
