package:
  name: pymodis
  version: "0.7.4"

source:
  fn: pyModis-0.7.4.tar.gz
  url: https://pypi.python.org/packages/source/p/pyModis/pyModis-0.7.4.tar.gz
  md5: 4763011446237487c26a9b3c4159b4fc
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pymodis = pymodis:main
    #
    # Would create an entry point called pymodis that calls pymodis.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools
    - gdal
    - numpy

  run:
    - python
    - gdal
    - numpy

test:
  # Python imports
  # imports:

  commands:
    - modis_download.py -h
    - modis_convert.py -h
    - modis_download_from_list.py -h
    - modis_mosaic.py -h
    - modis_multiparse.py -h
    - modis_parse.py -h
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pymodis.fem-environment.eu
  license: GNU General Public License v2 or later (GPLv2+)
  summary: 'Python library for MODIS data'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
