package:
  name: absl-py
  version: "0.1.10"

source:
  fn: absl-py-0.1.10.tar.gz
  url: https://pypi.python.org/packages/5f/b8/3dafc45f20a817ab9f042302646bcbe6f7e26e8a760871a85637e53a35ec/absl-py-0.1.10.tar.gz
  md5: 71fd85b74da723e36f7947e40462e9f4

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  imports:
    - absl
    - absl.flags
    - absl.logging
    - absl.testing

about:
  home: https://github.com/abseil/abseil-py
  license: Apache Software License
  summary: 'Abseil Python Common Libraries, see https://github.com/abseil/abseil-py.'
  license_family: APACHE
