{% set name="bazel" %}
{% set version="0.3.2" %}
{% set sha256="9692ac3318a40e8a0530f68bbfc473ae5f6a4a5c0fe08d2f88612ca4d40ba54a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/bazelbuild/bazel/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  ignore_prefix_files:
    - bin/bazel

requirements:
  build:
    - openjdk 8.0*
    - sed
    - unzip
    - zip 
    - gcc
  run:
    - openjdk 8.0*
    - libgcc

test:
  commands:
    - bazel -h

about:
  home: https://bazel.build
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Correct, reproducible, and fast builds for everyone
