package:
  name: jdk
  version: 1.8.0_60

source:
  fn: jdk-8u60-linux-x64.tar.gz
  url: file:///util/src/java/dist/jdk-8u60-linux-x64.tar.gz
  md5: b8ca513d4f439782c019cb78cd7fd101

build:
  binary_relocation: false

test:
  commands:
    - java -version
    - javac -version

about:
  home: http://www.java.com
  license: Oracle Binary Code License Agreement
