package:
    name: tensorflow-fma
    version: 1.3.1

source:
    fn: v1.3.1.tar.gz
    url: https://github.com/tensorflow/tensorflow/archive/v1.3.1.tar.gz
    md5: d351239b607b7a98c3660201921ba1c1
    patches:
        - librt.patch

build:
    number: 0
    skip: True # [osx]

requirements:
    build:
        - gcc # [linux]
        - llvm # [osx]
        - python
        - wheel
        - numpy >=1.11.0
        - bazel ==0.5.4
        - protobuf >=3.1.0
        - perl

    run:
        - libgcc # [linux]
        - python
        - numpy >=1.11.0
        - protobuf >=3.1.0


test:
    imports:
        - tensorflow

about:
    home: https://www.tensorflow.org
    license: Apache 2.0
    license_file: LICENSE
    summary: Computation using data flow graphs for scalable machine learning.
