{% set name = "aspera-cli" %}
{% set version = "3.9.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://download.asperasoft.com/download/sw/cli/3.9.2/ibm-aspera-cli-3.9.2.1426.c59787a-linux-64-release.sh  # [linux]
    sha256: 3f9e6ed10c208dea538b0053dec984538a8d08561915ee36739e5af5bb216a7f  # [linux]
  - url: https://download.asperasoft.com/download/sw/cli/3.9.2/ibm-aspera-cli-3.9.2.1426.c59787a-mac-10.7-64-release.sh  # [osx]
    sha256: 853e31219d2009677f2986a9944c8045d86941973b965b8bba9d3ad29d90ab30  # [osx]

build:
  number: 0

requirements:
  host:
  build:
  run:

test:
  commands:
    - ascp --help
    - ascp4 --help
    - aspera help

about:
  home: https://developer.asperasoft.com/desktop-advance/command-line-client
  license: Proprietary
  license_family: PROPRIETARY
  license_file: LICENSE-IBM-Aspera-CLI
  summary: "IBM Aspera Command-Line Interface (the Aspera CLI) is a collection of Aspera tools for performing high-speed, secure data transfers from the command line."
  # http://www-03.ibm.com/software/sla/sladb.nsf/displaylis/2ABD3328689EBBFE8525830C007A5F3
  # https://github.com/IBM/charts/blob/master/stable/ibm-aspera-cli/LICENSES/LICENSE-IBM-Aspera-CLI8
  notes: Please check post-build.sh for License details.
