{% set name = "scrappie" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name|lower }}_{{ version }}.tgz
  url: https://github.com/nanoporetech/{{ name|lower }}/archive/release-{{ version }}.tar.gz
  md5: 7a8b80232942c314d2ec19f8d595b627

build:
  number: 0
  skip: True # [py2k or linux]

requirements:
  build:
    - clang_osx-64
    - clangxx_osx-64
    - argp-standalone
    - python
    - numpy x.x
    - cffi >=1.0.0
    - perl
    - zlib {{ CONDA_ZLIB }}*
    - hdf5 {{ CONDA_HDF5 }}*
    - cunit
    - blas
    - cmake
    - openmp

  run:
    - libgcc
    - python
    - numpy x.x
    - cffi >=1.0.0
    - zlib {{ CONDA_ZLIB }}*
    - hdf5 {{ CONDA_HDF5 }}*
    - cunit
    - blas
    - openmp

test:
  commands:
    - scrappie help events

about:
  home: https://github.com/nanoporetech/scrappie
  license: Mozilla Public License 2.0 (MPL 2.0)
  license_file: LICENSE.md
  license_family: OTHER
  summary: Scrappie is a technology demonstrator for the Oxford Nanopore Research Algorithms group
