{% set name = "neper" %}
{% set version = "3.3.0" %}
{% set sha256 = "4da42dc2639b365c10f017e4b483c48bb563b1204a6b2d2282053cc6308b0c48" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://downloads.sourceforge.net/project/{{ name }}/{{ name }}-{{ version }}.tgz
    sha256: {{ sha256 }}
    patches:
      - isnan.patch

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - cmake
    - gsl
    - libmatheval
    - scotch
    - nlopt

  run:
    - gsl
    - libmatheval
    - gmsh
    - scotch
    - nlopt

test:
  commands:
    - neper --help

about:
  home: http://neper.sourceforge.net/index.html
  license: GPLv3
  license_family: GPL
  license_file: COPYING
  summary: "Neper is a software package for polycrystal generation and meshing."
