package:
  name: speex
  version: "1.2rc2"

source:
  url: http://downloads.xiph.org/releases/speex/speex-1.2rc2.tar.gz
  md5: 6ae7db3bab01e1d4b86bacfa8ca33e81

build:
    number: 0
    skip: True # [osx]

requirements:
  build:
    - gcc
    - libogg

  run:
    - libgcc
    - libogg

test:
  commands:
    - speexenc -v > /dev/null
    - speexdec -v > /dev/null

about:
  home: http://www.speex.org
  license: Xiph.Org BSD
  summary: "Speex: A Free Codec For Free Speech"

extra:
  skip-lints:
    - should_use_compilers
    - in_other_channels
