package:
  name: cutadapt
  version: !!str 1.5

source:
  fn: cutadapt-1.5.tar.gz
  url: https://pypi.python.org/packages/source/c/cutadapt/cutadapt-1.5.tar.gz
  md5: 639b86826778c14c8b1fe512f074b939
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cutadapt = cutadapt:main
    #
    # Would create an entry point called cutadapt that calls cutadapt.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - cutadapt
    - cutadapt.scripts

  commands:
    - cutadapt --version
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://code.google.com/p/cutadapt/
  license:  MIT License
  summary: 'trim adapters from high-throughput sequencing reads'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
