{% set name = "PHANOTATE" %}
{% set version = "2019.08.09" %}
{% set revision = "616af0756064f88637141812ddd1aed7915f3a12" %}
{% set sha256 = "81ab585cf497f024cf469a30918bcdcbda9e4eaf1ea83a69dc2adeba05d69703" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deprekate/PHANOTATE/archive/{{ revision }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - paths.patch

build:
  number: 0
  noarch: generic

requirements:
  run:
    - python
    - fastpath 2019.05.31

test:
  commands:
    - phanotate.py --help

about:
  home: https://github.com/deprekate/PHANOTATE
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: "PHANOTATE is a tool to annotate phage genomes."
  dev_url: https://github.com/deprekate/PHANOTATE
