{% set pkgname = "mro" %}
{% set version = "3.5.2" %}
{% set sha256 = "9bfd38a9d66028335ac166f7da939e2ea73f414f7a9b3fb800f02728f918fd31" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  url: https://mran.blob.core.windows.net/install/mro/{{ version }}/rhel/microsoft-r-open-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [osx]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - pango
    - fontconfig
    - cairo
    - expat
    - bzip2
    - zlib
    - xorg-libx11
    - xorg-libice
    - xorg-libsm
    - xorg-libxau
    - xorg-libxext
    - xorg-libxft
    - xorg-libxrender
    - xorg-libxt
    - xorg-libxcb

  run:
    - pango
    - fontconfig
    - cairo
    - expat
    - bzip2
    - zlib
    - xorg-libx11
    - xorg-libice
    - xorg-libsm
    - xorg-libxau
    - xorg-libxext
    - xorg-libxft
    - xorg-libxrender
    - xorg-libxt
    - xorg-libxcb

test:
  commands:
    - R --version
    - Rscript --version

about:
  home: https://mran.microsoft.com/open
  license: GPLv2
  license_family: GPL
  license_file: MRO_EULA.txt
  summary: "Microsoft R Open is the enhanced distribution of R from Microsoft Corporation."
