{% set version = "1.0.0" %}
{% set sha256 = "4cf9ea61be427ea71c346e438ad2871cf0c7671948819647ef8f182d54e955fe" %}

package:
  name: htstream
  version: {{ version }}

source:
  url: https://github.com/ibest/HTStream/archive/v{{ version }}-release.tar.gz
  sha256: {{ sha256 }}
  patches:
    - cmake.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - cmake
    - boost
    - zlib
    - bzip2
    - xz

  run:
    - boost
    - zlib
    - bzip2
    - xz

test:
  commands:
    - hts_AdapterTrimmer
    - hts_CutTrim
    - hts_NTrimmer
    - hts_Overlapper
    - hts_PolyATTrim
    - hts_QWindowTrim
    - hts_SeqScreener
    - hts_Stats
    - hts_SuperDeduper

about:
  home: https://github.com/ibest/HTStream
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: "A toolset for high throughput sequence analysis using a streaming approach facilitated by Linux pipes."
