package:
  name: azcopy
  version: 7.2.0

source:
  url: https://aka.ms/downloadazcopylinuxrhel6
  fn: azure.tar.gz
  sha256: 1ded64bb733d58ff4c634511ff486068516a093177b7d4382db60d00d68ab74b

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - openssl

  run:
    - openssl

test:
  commands:
    - azcopy --version | grep azcopy 2>&1

about:
  home: http://aka.ms/azcopy
  license: PROPRIETARY
  license_family: PROPRIETARY
  license_file: azcopy/LICENSE
  summary: "AzCopy is a command-line utility designed for copying data to/from Microsoft Azure Blob and File storage, using simple commands designed for optimal performance."

extra:
  skip-lints:
    - should_not_use_fn
