about:
  home: https://github.com/Magdoll/Cogent
  license:  GNU General Public License (GPL)
  summary: 'Cogent is a tool for reconstructing the coding genome using high-quality full-length transcriptome sequences.'

build:
  number: 0
  skip: True # [py3k or osx]

package:
  name: md-cogent
  version: 3.1

requirements:
  build:
  - python
  - numpy
  - gcc
  run:
  - python
  - numpy
  - libgcc
  - libgfortran 1.0*

source:
  fn: v3.1.tar.gz
  md5: c0829d1dcd1a879b4368e60c46866088
  url: https://github.com/Magdoll/Cogent/archive/v3.1.tar.gz

test:
  # Python imports
  imports:
    - Cogent
