package:
    name: rproject
    version: 3.1.2

source:
    fn: R-3.1.2.tar.gz
    url: http://rweb.quant.ku.edu/cran/src/base/R-3/R-3.1.2.tar.gz
    md5: 3af29ec06704cbd08d4ba8d69250ae74

build:
    number: 0

requirements:
    build:
        - tk
        - jdk

    run:
        - tk
        - jdk

test:
    commands:
        - R -h
        - R --version
        - Rscript --version

about:
    home: http://www.r-project.org/
    license: GPL
