package:
  name: r-glue
  version: "1.1.1"

source:
  fn: glue_1.1.1.tar.gz 
  url:
    - https://cran.r-project.org/src/contrib/glue_1.1.1.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/glue/glue_1.1.1.tar.gz

build:
  number: 0
  skip: True # [osx]
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r >=3.0
    - gcc # [linux]
    - llvm # [osx]

  run:
    - r >=3.0
    - libgcc # [linux]

test:
  commands:
    - $R -e "library('glue')"

about:
  home: https://cran.r-project.org/web/packages/glue/index.html
  license: Custom OSS
  summary: An implementation of interpreted string literals.
  license_family: Other
