{% set name = "perl-schedule-sgelk" %}
{% set version = "2019.01.28" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/lskatz/Schedule--SGELK.git
  git_rev: 83ca0588e41515f27ea5135fbd5bc89d01c54a78

build:
  number: 0
  skip: True  # [osx]

requirements:
  host:
    - perl 5.26
  run:
    - perl 5.26
    - perl-data-dumper
    - perl-file-spec
    - perl-file-slurp
    - perl-file-temp
    - perl-string-escape

test:
  imports:
    - Schedule::SGELK

about:
  home: https://github.com/lskatz/Schedule--SGELK
  license: Custom OSS
  summary: "Perl module for scheduling tasks, with only using qsub/qstat/qdel."

extra:
  skip-lints:
    - uses_git_url
    - missing_hash
