package:
  name: r-influencer
  version: "0.1.0"

source:
  fn: influenceR_0.1.0.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/influenceR_0.1.0.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/influenceR/influenceR_0.1.0.tar.gz

build:
  number: 0
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-matrix >=1.1_4
    - r-igraph >=1.0.1
    - gcc # [linux]

  run:
    - r-base
    - r-matrix >=1.1_4
    - r-igraph >=1.0.1
    - libgcc # [linux]

test:
  commands:
    - $R -e "library('influenceR')"

about:
  home: https://github.com/rcc-uchicago/influenceR
  license: GPL-2
  summary: Provides functionality to compute various node centrality measures on networks. Included
    are functions to compute betweenness centrality (by utilizing Madduri and Bader's
    SNAP library), implementations of Burt's constraint and effective network size (ENS)
    metrics, Borgatti's algorithm to identify key players, and Valente's bridging metric.
    On Unix systems, the betweenness, Key Players, and bridging implementations are
    parallelized with OpenMP, which may run faster on systems which have OpenMP configured.
  license_family: GPL2
