package:
  name: vo-amrwbenc
  version: 0.1.3

source:
  fn: vo-amrwbenc-0.1.3.tar.gz
  url: http://downloads.sourceforge.net/project/opencore-amr/vo-amrwbenc/vo-amrwbenc-0.1.3.tar.gz
  md5: f63bb92bde0b1583cb3cb344c12922e0
	
build:
    number: 0
	  
requirements:
  build:
    - gcc
  run:
    - libgcc

test:
  commands:
    - test -f ${PREFIX}/lib/libvo-amrwbenc.so
    - test -f ${PREFIX}/lib/libvo-amrwbenc.a

about:
  home: http://opencore-amr.sourceforge.net
  license: Apache 2.0
  license_file: COPYING
  summary: "VisualOn AMR-WB encoder library"
