{% set name = "nextcloud-client" %}
{% set version = "3.0.2" %}
{% set sha256 = "07d8111e47c8b6351f7074355e091342363262f93d81ce3ce45dd1ef8e6a69bd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nextcloud/desktop/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [ osx ]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - sphinx
    - doxygen
    - graphviz
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - zlib
    - qt
    - qtkeychain
    - openssl
    - sqlite
    - xorg-libxfixes  # [linux]
    - alsa-lib
    - xorg-libxcursor
    - xorg-libxcomposite
    - xorg-libxrender
    - xorg-libxi
    - xorg-libxtst
    - xorg-libxscrnsaver
  run:
    - zlib
    - qt
    - qtkeychain
    - openssl
    - sqlite
    - alsa-lib
    - xorg-libxcursor
    - xorg-libxcomposite
    - xorg-libxrender
    - xorg-libxi
    - xorg-libxtst
    - xorg-libxscrnsaver

test:
  commands:
    - nextcloudcmd --help

about:
  home: http://www.nextcloud.com
  dev_url: https://github.com/nextcloud/desktop
  license: GPL
  license_family: GPL
  license_file: COPYING
  summary: "The Nextcloud Desktop Client is a tool to synchronize files from Nextcloud Server with your computer."
