{% set name = "perl-fast" %}
{% set version = "1.06" %}
{% set sha256 = "7b5bff1e1220971a93a8c34059540328d1ac0ea65c33d195ade961c9236b995c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/D/DH/DHARD/FAST-1.06.tar.gz
  sha256: {{ sha256 }}
  patches:
    - perl.patch

build:
  noarch: generic
  number: 0

requirements:
  host:
    - perl >=5.26.2
    - perl-pod-usage
    - perl-sort-mergesort
    - perl-extutils-makemaker
    - perl-sort-key
    - perl-bit-vector
  run:
    - perl >=5.26.2
    - perl-pod-usage
    - perl-sort-mergesort
    - perl-extutils-makemaker
    - perl-sort-key
    - perl-bit-vector

test:
  imports:
    - FAST
  commands:
    - alnpi --version
    - fasconvert --version
    - gbfalncut --version

about:
  home: http://metacpan.org/pod/FAST
  license: perl_5
  summary: 'FAST Analysis of Sequences Toolbox'
