{% set name = "perl-sort-key" %}
{% set version = "1.33" %}
{% set sha256 = "ed6a4ccfab094c9cd164f564024e98bd21d94f4312ccac4d6246d22b34081acf" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/SA/SALVA/Sort-Key-1.33.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl
    - perl-extutils-makemaker

about:
  home: http://metacpan.org/pod/Sort::Key
  license: perl_5
  summary: "The fastest way to sort anything in Perl"
