{% set prefix = "octave" %}
{% set name = "struct" %}
{% set version = "1.0.14" %}
{% set sha256 = "ad4e17687bc24650f032757271b20b70fe32c35513d4dd9ab1e549919df36b47" %}

package:
  name: {{ prefix }}-{{ name }}
  version: {{ version }}

source:
  url: https://octave.sourceforge.io/download.php?package={{ name }}-{{ version }}.tar.gz
  folder: {{ name }}-{{ version }}
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True # [osx]
  script:
    - sudo yum install -y -q mesa-libGLU-devel mesa-libGL-devel
    - tar -czf {{ name }}-{{ version }}.tar.gz {{ name }}-{{ version }}
    - octave -W -H --eval "pkg install -verbose {{ name }}-{{ version }}.tar.gz"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - octave
  run:
    - octave

test:
  commands:
    - octave -W -H --eval 'pkg load {{ name }}'

about:
  home: https://octave.sourceforge.io/{{ name }}/index.html
  license: GPLv3
  license_family: GPL
  license_file: {{ name }}-{{ version }}/COPYING
  doc_url: https://octave.sourceforge.io/{{ name }}/overview.html
  summary: 'Additional structure manipulation functions.'
