package:
  name: r-rlang
  version: "0.1.2"

source:
  fn: rlang_0.1.2.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rlang_0.1.2.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rlang/rlang_0.1.2.tar.gz

build:
  number: 0
  skip: True # [osx]
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r >=3.1
    - gcc # [linux]
    - llvm # [osx]

  run:
    - r >=3.1
    - libgcc # [linux]

test:
  commands:
    - $R -e "library('rlang')"

about:
  home: https://cran.r-project.org/web/packages/rlang/index.html
  license: GPL-3
  summary: A toolbox for working with base types, core R features like the condition system, and core 'Tidyverse' features like tidy evaluation.
  license_family: GPL3
