{% set name = "xcrysden" %}
{% set version = "1.5.60" %}
{% set buildnum = "1" %}
{% set sha256 = "a695729f1bb3e486b86a74106c06a392c8aca048dc6b0f20785c3c311cfb2ef4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}-linux_x86_64-semishared.tar.gz
  url: http://www.xcrysden.org/download/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - topdir.patch
    - makefile.patch
    - wget.patch

build:
  number: {{ buildnum }}
  skip: True # [osx]

requirements:
  build:
    - gcc # [linux]
    - wget
    - gettext
    - libxcb
    - libuuid
    - libiconv
    - icu
    - xorg-libice
    - xorg-libsm
    - xorg-libx11
    - xorg-libxau
    - xorg-libxdmcp
    - xorg-libxext
    - xorg-libxft
    - xorg-libxmu
    - xorg-libxrender
    - xorg-libxscrnsaver
    - xorg-libxt
    - fontconfig
    - freetype
    - zlib {{ CONDA_ZLIB }}*
    - bzip2 {{ CONDA_BZIP2 }}*
    - xz {{ CONDA_XZ }}*
    - libpng 1.6*
    - libxml2
    - tk 8.5*
    - fftw 3.3*

  run:
    - libgcc # [linux]
    - libxcb
    - libuuid
    - libiconv
    - icu
    - xorg-libice
    - xorg-libsm
    - xorg-libx11
    - xorg-libxau
    - xorg-libxdmcp
    - xorg-libxext
    - xorg-libxft
    - xorg-libxmu
    - xorg-libxrender
    - xorg-libxscrnsaver
    - xorg-libxt
    - fontconfig
    - freetype
    - zlib {{ CONDA_ZLIB }}*
    - bzip2 {{ CONDA_BZIP2 }}*
    - xz {{ CONDA_XZ }}*
    - libpng 1.6*
    - libxml2
    - tk 8.5*
    - fftw 3.3*

test:
  commands:
    - xcrysden --help
    - conda inspect linkages -p $PREFIX $PKG_NAME

about:
  home: http://www.xcrysden.org/XCrySDen.html
  license: GPLv2
  license_family: GPL
  license_file: COPYRIGHT
  summary: 'XCrySDen is a crystalline and molecular structure visualisation program aiming at display of isosurfaces and contours, which can be superimposed on crystalline structures and interactively rotated and manipulated.'
