package:
  name: r-sendmailr
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.2_1"

source:
  fn: sendmailR_1.2-1.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/sendmailR_1.2-1.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/sendmailR/sendmailR_1.2-1.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r ==3.1.2
    - r-base64enc

  run:
    - r ==3.1.2
    - r-base64enc

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('sendmailR')" # [not win]
    - "\"%R%\" -e \"library('sendmailR')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: GPL-2
  summary: !!python/unicode 'Package contains a simple SMTP client which provides a portable
    solution for sending email, including attachment, from within R.'


# The original CRAN metadata for this package was:

# Package: sendmailR
# Version: 1.2-1
# Title: send email using R
# Description: Package contains a simple SMTP client which provides a portable solution for sending email, including attachment, from within R.
# Authors@R: c(person("Olaf", "Mersmann", role=c("aut", "cre"), email="olafm@p-value.net"), person("Quinn", "Weber", role="ctb"))
# Depends: R (>= 3.0.0)
# Imports: base64enc
# License: GPL-2
# LazyData: yes
# Packaged: 2014-09-21 11:16:23 UTC; olafm
# Author: Olaf Mersmann [aut, cre], Quinn Weber [ctb]
# Maintainer: Olaf Mersmann <olafm@p-value.net>
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-09-21 13:32:55

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
