package:
  name: blast [linux64]
  version: 2.2.26

source:
  fn: blast-2.2.26-x64-linux.tar.gz
  url: ftp://ftp.ncbi.nlm.nih.gov/blast/executables/release/2.2.26/blast-2.2.26-x64-linux.tar.gz 
  md5: 809798a912f4fb37f62406201456df67

build:
  number: 0

about:
  home: http://blast.ncbi.nlm.nih.gov
  license: Public Domain

# vim:set ts=8 sw=2 
