package:
  name: scientificpython
  version: 2.8.1

source:
  fn: ScientificPython-2.8.1.tar.gz
  url: https://sourcesup.renater.fr/frs/download.php/file/4411/ScientificPython-2.8.1.tar.gz
  md5: 73ee0df19c7b58cdf2954261f0763c77

build:
  number: 1
  skip: True #[py3k]

requirements:
  build:
    - python
    - libnetcdf
    - numpy x.x
    - gcc

  run:
    - python
    - libnetcdf
    - numpy x.x
    - libgcc

test:
  # Python imports
  imports:
    - Scientific


about:
  home: http://dirac.cnrs-orleans.fr/ScientificPython/
  license: CeCILL-C FREE SOFTWARE LICENSE AGREEMENT
  summary: 'ScientificPython is a collection of Python modules that are useful for scientific computing.'

