package:
  name: blast [linux64]
  version: 2.2.22

source:
  fn: blast-2.2.22-x64-linux.tar.gz
  url: ftp://ftp.ncbi.nlm.nih.gov/blast/executables/release/2.2.22/blast-2.2.22-x64-linux.tar.gz 
  md5: 84e900b276a6e956dbbff9e6321155cf 

build:
  number: 0

about:
  home: http://blast.ncbi.nlm.nih.gov
  license: Public Domain

# vim:set ts=8 sw=2 
