{% set name = "libminc" %}
{% set version = "2.3.00" %}
{% set sha256 = "8c00e0383575ace1f941a5b35b99678db2a0dd5e023f8671d25debc949c7cf12" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  - url: https://github.com/BIC-MNI/{{ name|lower }}/archive/{{ name }}-{{ version|replace(".","-") }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - hdf5 1.8*
    - libnetcdf 4.*
    - zlib
    - cmake

  run:
    - hdf5 1.8*
    - libnetcdf 4.*
    - zlib

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME

about:
  home:  https://github.com/BIC-MNI/libminc
  license: Custom OSS
  license_family: OTHER
  license_file: COPYING
  summary: "libminc is the core library and API of the MINC toolkit"
