{% set version = '1.4.1' %}

package:
  name: r-celestial
  version: {{ version|replace("-", "_") }}

source:
  fn: celestial_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/celestial_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/celestial/celestial_{{ version }}.tar.gz
  sha256: 7f1e0a607f4683519a0d3576de1f33d5fdc9e0d7c8e87e1a4b5203498b9a6e33

build:
  number: 0
  skip: true  # [osx]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-nistunits
    - r-rann
    - r-pracma
  run:
    - r-base
    - r-nistunits
    - r-rann
    - r-pracma

test:
  commands:
    - $R -e "library('celestial')"  # [linux]

about:
  home: https://CRAN.R-project.org/package=celestial
  license: GPL-3
  summary: Contains a number of common astronomy conversion routines, particularly the HMS and
    degrees schemes, which can be fiddly to convert between on mass due to the textural
    nature of the former. It allows users to coordinate match datasets quickly. It also
    contains functions for various cosmological calculations.
  license_family: GPL3
