package:
  name: r-bindr
  version: "0.1"

source:
  fn: bindr_0.1.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/bindr_0.1.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/bindr/bindr_0.1.tar.gz

build:
  number: 0
  skip: True # [osx]
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r >=3.1
    - gcc # [linux]
    - llvm # [osx]

  run:
    - r >=3.1
    - libgcc # [linux]

test:
  commands:
    - $R -e "library('bindr')"

about:
  home: https://cran.r-project.org/web/packages/bindr/index.html
  license: Custom OSS
  summary: Provides a simple interface for creating active bindings where the bound function accepts additional arguments.
  license_family: Other
