{% set name = "vxl" %}
{% set version = "1.17.0" %}
{% set sha256 = "8ae7edab50263bc91fda779c909bc87e331d4e3d288660eb13bb61e090646b95" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  - url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version}}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - zlib
    - cmake
    - bzip2
    - expat =2.1
    - libpng

  run:
    - zlib
    - bzip2
    - expat =2.1
    - libpng

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME

about:
  home: http://vxl.sourceforge.net
  license: Custom OSS
  license_family: OTHER
  license_file: core/vxl_copyright.h
  summary: "VXL (the Vision-something-Libraries) is a collection of C++ libraries designed for computer vision research and implementation."
