package:
  name: cdbtools [linux64]
  version: 0.99

source:
  fn:  cdbfasta.tar.gz
  url: ftp://occams.dfci.harvard.edu/pub/bio/tgi/software/cdbfasta/cdbfasta.tar.gz 
  md5: ed07e474d67e0e79e7e89f9f43ee96df 

build:
  number: 0

test:
  commands:
    - cdbfasta -v
    - cdbyank -v

about:
  home: http://compbio.dfci.harvard.edu/tgi
  license: Public Domain

# vim:set ts=8 sw=2 
