{% set name = "szip" %}
{% set version = "2.1.1" %}
{% set sha256 = "21ee958b4f2d4be2c9cabfa5e1a94877043609ce86fde5f286f105f7ff84d412" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://support.hdfgroup.org/ftp/lib-external/{{ name }}/{{ version }}/src/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - gcc # [linux]
    - llvm # [osx]

  run:
    - libgcc # [linux]

test:
  commands:
    - conda inspect linkages -p ${PREFIX} szip

about:
  home: https://support.hdfgroup.org/doc_resource/SZIP
  license: Proprietary
  summary: 'Szip is an implementation of the extended-Rice lossless compression algorithm.'
  license_family: PROPRIETARY
