{% set name = "AGFusion" %}
{% set version = "1.0" %}
{% set sha256 = "2ede97b11ddcb0980dc251c34577ec16a70106d1cf3e2b6cdea66ee208e6835e" %}

about:
  home: https://github.com/murphycj/AGFusion
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: AGFusion is a python package for annotating gene fusions from the human or mouse genomes.

build:
  number: 0

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  url: https://github.com/murphycj/{{ name }}/archive/v{{ version }}.tar.gz

requirements:
  build:
    - python
    - matplotlib >=1.5.0
    - pandas >=0.18.1
    - biopython >=1.67
    - nose2 >=0.6.5
    - future >=0.16.0
    - pyensembl >=1.1.0
  run:
    - python
    - matplotlib >=1.5.0
    - pandas >=0.18.1
    - biopython >=1.67
    - nose2 >=0.6.5
    - future >=0.16.0
    - pyensembl >=1.1.0

test:
  commands:
    - agfusion -h
  imports:
    - agfusion

extra:
  doi: doi.org/10.1101/080903
