{% set name = "bitmath" %}
{% set version = "1.3.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 293325f01e65defe966853111df11d39215eb705a967cb115851da8c4cfa3eb8

build:
  number: 0
  noarch: python
  entry_points:
    - bitmath = bitmath:cli_script
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - bitmath
  commands:
    - bitmath --help

about:
  home: https://github.com/tbielawa/bitmath
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pythonic module for representing and manipulating file sizes with different prefix notations (file size unit conversion).
