package:
  name: scikits.samplerate
  version: 0.3.3

source:
  fn: scikits.samplerate-0.3.3.tar.gz
  url: https://pypi.python.org/packages/source/s/scikits.samplerate/scikits.samplerate-0.3.3.tar.gz
  md5: 96c8d8ba3aa95a9db15994f78792efb4

build:
  number: 0
  skip: True [py3k]

requirements:
  build:
    - python
    - numpy
    - libsamplerate

  run:
    - python
    - numpy
    - libsamplerate

test:
  # Python imports
  imports:
    - scikits.samplerate

about:
  home: http://www.ar.media.kyoto-u.ac.jp/members/david/softwares/samplerate
  license: GPL
  summary: A python module for high quality audio resampling
