package:
  name: ksnp
  version: "3.1"

source:
  fn: kSNP3.1_Linux_package.zip
  url: https://sourceforge.net/projects/ksnp/files/kSNP3.1_Linux_package.zip
  md5: ccfa894d378a3c3871ff011a49010fe0
  patches:
    - path.patch

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
     - perl
     
  run:
     - perl

test:
  commands:
     - kSNP3 2>&1 | grep kSNP3 > /dev/null

about:
  home: https://sourceforge.net/projects/ksnp/
  license: BSD
  summary: kSNP identifies the pan-genome SNPs in a set of genome sequences, and estimates phylogenetic trees based upon those SNPs.
