{% set name = "cuda-driver" %}
{% set version = "375.66" %}
{% set sha256 = "a500746bfd4fd1d144cf826d5b5882d1298e8555ad9124a96921181c9a87bbb7" %}
{% set fn="6fhaba1mddryjgnfon40zf9f08sclfqd.tgz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ fn }}
  url: https://unl.box.com/shared/static/{{ fn }}
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True # [osx]

requirements:
  build:

  run:

test:
  commands:
    - nvidia-settings -v

about:
  home: http://www.nvidia.com/drivers
  license: Custom
  summary: 'NVIDIA linux driver'
