{% set name = "tensorpack" %}
{% set version = "0.9.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: bc6566c12471a0f9c0a79acc3d045595b1943af8e423c5b843986b73bfe5425f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - functools32   # [ py < 30 ]
    - msgpack-python >=0.5.2
    - msgpack-numpy >=0.4.4.2
    - numpy >=1.14
    - pip
    - psutil >=5
    - python
    - pyzmq >=16
    - six
    - subprocess32   # [ py < 30 ]
    - tabulate >=0.7.7
    - termcolor >=1.1
    - tqdm >4.29.0
  run:
    - functools32   # [ py < 30 ]
    - msgpack-python >=0.5.2
    - msgpack-numpy >=0.4.4.2
    - numpy >=1.14
    - psutil >=5
    - python
    - pyzmq >=16
    - six
    - subprocess32   # [ py < 30 ]
    - tabulate >=0.7.7
    - termcolor >=1.1
    - tqdm >4.29.0
  run_constrained:
    - tensorflow >=1.3,<=2
    - tensorflow-gpu >=1.3,<=2

test:
  imports:
    - tensorpack
    - tensorpack.callbacks
    - tensorpack.compat
    - tensorpack.contrib
    - tensorpack.dataflow
    - tensorpack.dataflow.dataset
    - tensorpack.dataflow.imgaug
    - tensorpack.graph_builder
    - tensorpack.input_source
    - tensorpack.models
    - tensorpack.predict
    - tensorpack.tfutils
    - tensorpack.train
    - tensorpack.utils
  requires:
    - flake8
    - scikit-image
    - tensorflow>=1.3,<2

about:
  home: "https://github.com/tensorpack/tensorpack"
  license: Apache
  license_family: APACHE
  license_file: LICENSE
  summary: "A Neural Network Training Interface on TensorFlow"
  doc_url: "https://tensorpack.readthedocs.io/index.html"
