package:
  name: r-viridislite
  version: "0.2.0"

source:
  fn: viridisLite_0.2.0.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/viridisLite_0.2.0.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/viridisLite/viridisLite_0.2.0.tar.gz

build:
  number: 0
  skip: True # [osx]
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r

  run:
    - r

test:
  commands:
    - $R -e "library('viridisLite')"

about:
  home: https://github.com/sjmgarnier/viridisLite
  license: MIT + file LICENSE
  summary: Port of the new 'matplotlib' color maps ('viridis' - the default -, 'magma', 'plasma'
    and 'inferno') to 'R'. 'matplotlib' <http://matplotlib.org/ > is a popular plotting
    library for 'python'. These color maps are designed in such a way that they will
    analytically be perfectly perceptually-uniform, both in regular form and also when
    converted to black-and-white. They are also designed to be perceived by readers
    with the most common form of color blindness. This is the 'lite' version of the
    more complete 'viridis' package that can be found at <https://cran.r-project.org/package=viridis>.
  license_family: MIT
