{% set name="bazel" %}
{% set version="0.10.0" %}
{% set sha256="47e0798caaac4df499bce5fe554a914abd884a855a27085a4473de1d737d9548" %}

package:
  name: {{ name }}
  version: {{ version }}
source:
  url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel-{{ version }}-dist.zip
  sha256: {{ sha256 }}

build:
  ignore_prefix_files:
    - bin/bazel
  binary_relocation: False
  skip: True # [osx]

requirements:
  build:
    - openjdk 8.0*
    - sed
    - unzip
    - zip
    - gcc
    - gmp {{CONDA_GMP}}*
  run:
    - openjdk 8.0*
    - libgcc
    - gmp {{CONDA_GMP}}*

test:
  commands:
    - bazel -h

about:
  home: https://bazel.build
  license: Apache-2.0
  license_file: LICENSE
  summary: Correct, reproducible, and fast builds for everyone
