{% set name = "perl-logger-simple" %}
{% set version = "2.0" %}
{% set sha256 = "2e63fd3508775b5902132ba1bfb03b42bee468dfaf35dfe42e1909ff6d291b2d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/T/TS/TSTANLEY/Logger-Simple-2.0.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - perl
    - perl-carp
    - perl-test-pod
    - perl-time-hires
    - perl-test-harness
    - perl-object-insideout

  run:
    - perl
    - perl-carp
    - perl-test-harness
    - perl-time-hires
    - perl-object-insideout
    - perl-test-pod

test:
  # Perl 'use' tests
  imports:
    - Logger::Simple

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/Logger::Simple
  license: perl5
  summary: 'Implementation of the Simran-Log-Log and Simran-Error-Error modules'
