package:
  name: r-diagrammer
  version: "0.9.0"

source:
  fn: DiagrammeR_0.9.0.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/DiagrammeR_0.9.0.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/DiagrammeR/DiagrammeR_0.9.0.tar.gz

build:
  number: 0
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r
    - r-rcolorbrewer >=1.1_2
    - r-dplyr >=0.5.0
    - r-htmlwidgets >=0.8
    - r-igraph >=1.0.1
    - r-influencer >=0.1.0
    - r-magrittr >=1.5
    - r-rgexf >=0.15.3
    - r-rstudioapi >=0.6
    - r-scales >=0.4.1
    - r-stringr >=1.1.0
    - r-tibble >=1.2
    - r-viridis >=0.3.4
    - r-visnetwork >=1.0.2

  run:
    - r
    - r-rcolorbrewer >=1.1_2
    - r-dplyr >=0.5.0
    - r-htmlwidgets >=0.8
    - r-igraph >=1.0.1
    - r-influencer >=0.1.0
    - r-magrittr >=1.5
    - r-rgexf >=0.15.3
    - r-rstudioapi >=0.6
    - r-scales >=0.4.1
    - r-stringr >=1.1.0
    - r-tibble >=1.2
    - r-viridis >=0.3.4
    - r-visnetwork >=1.0.2

test:
  commands:
    - $R -e "library('DiagrammeR')"

about:
  home: https://github.com/rich-iannone/DiagrammeR
  license: MIT + file LICENSE
  summary: Create graph diagrams and flowcharts using R.
  license_family: MIT
