package:
  name: r-viridis
  version: "0.4.0"

source:
  fn: viridis_0.4.0.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/viridis_0.4.0.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/viridis/viridis_0.4.0.tar.gz

build:
  number: 0
  skip: True # [osx]
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r
    - r-ggplot2 >=1.0.1
    - r-gridextra
    - r-viridislite >=0.2.0

  run:
    - r
    - r-ggplot2 >=1.0.1
    - r-gridextra
    - r-viridislite >=0.2.0

test:
  commands:
    - $R -e "library('viridis')"

about:
  home: https://github.com/sjmgarnier/viridis
  license: MIT + file LICENSE
  summary: Port of the new 'matplotlib' color maps ('viridis' - the default -, 'magma', 'plasma'
    and 'inferno') to 'R'. 'matplotlib' <http://matplotlib.org/ > is a popular plotting
    library for 'python'. These color maps are designed in such a way that they will
    analytically be perfectly perceptually-uniform, both in regular form and also when
    converted to black-and-white. They are also designed to be perceived by readers
    with the most common form of color blindness.
  license_family: MIT
