package:
  name: pydicom
  version: "0.9.9"

source:
  fn: pydicom-0.9.9.tar.gz
  url: https://pypi.python.org/packages/5d/1d/dd9716ef3a0ac60c23035a9b333818e34dec2e853733d03f502533af9b84/pydicom-0.9.9.tar.gz
  md5: a66ca6728e69ba565ab9c8a21740eee8

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - dicom
    - dicom.contrib
    - dicom.examples
    - dicom.test
    - dicom.test.performance
    - dicom.util

about:
  home: http://pydicom.googlecode.com
  license: MIT License
  summary: 'Pure python package for DICOM medical file reading and writing'
  license_family: MIT
