package:
  name: r-biom
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.3.12"

source:
  fn: biom_0.3.12.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/biom_0.3.12.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/biom/biom_0.3.12.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat (>= 0.7.1), knitr (>= 1.3)
requirements:
  build:
    - r ==3.1.2
    - r-matrix >=1.0.12 # [not win]
    - r-rjsonio >=1.0.3
    - r-plyr >=1.8

  run:
    - r ==3.1.2
    - r-matrix >=1.0.12 # [not win]
    - r-rjsonio >=1.0.3
    - r-plyr >=1.8

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('biom')" # [not win]
    - "\"%R%\" -e \"library('biom')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: !!python/unicode 'https://github.com/joey711/biom/, http://biom-format.org/'

  license: GPL-2
  summary: !!python/unicode 'This is an R package for interfacing with the BIOM format. This
    package includes basic tools for reading biom-format files, accessing and subsetting
    data tables from a biom object (which is more complex than a single table), as well
    as limited support for writing a biom-object back to a biom-format file. The design
    of this API is intended to match the python API and other tools included with the
    biom-format project, but with a decidedly "R flavor" that should be familiar to
    R users. This includes S4 classes and methods, as well as extensions of common core
    functions/methods.'


# The original CRAN metadata for this package was:

# Package: biom
# Version: 0.3.12
# Date: 2014-02-23
# Maintainer: Paul J. McMurdie <mcmurdie@stanford.edu>
# License: GPL-2
# Title: An interface package (beta) for the BIOM file format.
# Type: Package
# Author: Paul J. McMurdie <mcmurdie@stanford.edu> and the biom-format team http://biom-format.org/
# BugReports: https://github.com/joey711/biom/issues
# URL: https://github.com/joey711/biom/, http://biom-format.org/
# Description: This is an R package for interfacing with the BIOM format. This package includes basic tools for reading biom-format files, accessing and subsetting data tables from a biom object (which is more complex than a single table), as well as limited support for writing a biom-object back to a biom-format file. The design of this API is intended to match the python API and other tools included with the biom-format project, but with a decidedly "R flavor" that should be familiar to R users. This includes S4 classes and methods, as well as extensions of common core functions/methods.
# Imports: plyr (>= 1.8), RJSONIO (>= 1.0.3), Matrix (>= 1.0.12)
# Depends: R (>= 3.0.0), methods
# Suggests: testthat (>= 0.7.1), knitr (>= 1.3)
# VignetteBuilder: knitr
# Collate: 'allClasses.R' 'allPackage.R' 'IO-methods.R' 'BIOM-class.R' 'validity-methods.R'
# Packaged: 2014-02-23 23:09:16 UTC; pjm2
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-02-24 01:20:23

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
