package:
  name: swarm [linux64]
  version: 1.2.19

source:
  fn: 1.2.19.tar.gz
  url: https://github.com/torognes/swarm/archive/1.2.19.tar.gz
  md5: 4d147b9c94b8966760d0b737499a53d2

build:
  number: 0

requirements:
  run:
    - python

test:
  commands:
     - swarm_breaker.py --version

about:
  home: https://github.com/torognes/swarm
  license: Affero GPL

# vim:set ts=8 sw=2 
