{% set name = "dm-sonnet" %}
{% set version = "1.19" %}
{% set sha256 = "2ea785babfc9db5a07f3fbfe677d5f2dcc20ed3dbbb1bb3c0cd198b816bf84c7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
    fn: v{{ version }}.tar.gz
    url: https://github.com/deepmind/sonnet/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0
    skip: True # [osx]

requirements:
    build:
        - gcc # [linux]
        - llvm # [osx]
        - python
        - wheel
        - tensorflow >=1.2
        - bazel >=0.4.5
        - absl-py

    run:
        - libgcc # [linux]
        - python
        - tensorflow >=1.2
        - six
        - absl-py

test:
    imports:
        - sonnet

about:
    home: https://deepmind.github.io/sonnet
    license: Apache 2.0
    license_file: LICENSE
    summary: Sonnet is a library built on top of TensorFlow for building complex neural networks.
