octave:
  - 4.0.*
octave_struct:
  - 1.0.*
octave_statistics:
  - 1.3.*

pin_run_as_build:
  octave:
    max_pin: x.x
    min_pin: x.x.x
  octave_struct:
    max_pin: x.x
    min_pin: x.x.x
  octave_statistics:
    max_pin: x.x
    min_pin: x.x.x
