{% set name = "delly" %}
{% set version = "0.8.3" %}
{% set sha256 = "6a9f1db34a51e0a79ff119f1894c3857b5142e8270c18022707cb000788cbdf0" %}

package:
  name: {{ name|lower }}-omp
  version: {{ version }}

source:
  url: https://github.com/dellytools/delly/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - boost-cpp
    - htslib
    - openmp
  run:
    - boost-cpp
    - htslib
    - openmp

test:
  commands:
    - delly --help

about:
  home: https://github.com/dellytools/delly
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Structural variant discovery by integrated paired-end and split-read analysis."
  description: "Delly is an integrated structural variant (SV) prediction method that can discover, genotype and visualize deletions, tandem duplications, inversions and translocations at single-nucleotide resolution in short-read massively parallel sequencing data."
  dev_url: https://github.com/dellytools/delly

extra:
  identifiers:
    - doi:10.1093/bioinformatics/bts378
