{% set name = "inla" %}
{% set version = "20.03.17" %}
{% set sha256 = "0d594b78aefefce05c6693f89e1af725a9164eecc825d3e85cee7860b108d1fc" %}

package:
  name: {{ name }}
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://github.com/unlhcc/r-inla/archive/Version_20.03.17.tar.gz
  sha256: {{ sha256 }}
  patches:
    - muparser.patch

build:
  number: 0
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/
  skip: True # [osx]

requirements:
  build:
    - make
    - rsync
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}

  host:
    - r-base {{ r_base }}
    - r-mathlib {{ r_base }}
    - gmrflib
    - gsl
    - zlib
    - taucs
    - metis
    - suitesparse
    - muparser
    - libblas
    - libcblas
    - liblapack

  run:
    - r-base
    - r-mathlib
    - gmrflib
    - gsl
    - zlib
    - taucs
    - metis
    - suitesparse
    - muparser

test:
  commands:
    - inla -h

about:
  home: http://www.r-inla.org/
  dev_url: http://bitbucket.org/hrue/r-inla
  license: GPL-2
  summary: "Full Bayesian Analysis of Latent Gaussian Models using Integrated Nested Laplace Approximations"
  license_family: GPL2
  license_file: r-inla.org/license/license.txt
