package:
  name: r-vegan
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "2.3_0"

source:
  fn: vegan_2.3-0.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/vegan_2.3-0.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/vegan/vegan_2.3-0.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: parallel, tcltk
requirements:
  build:
    - r ==3.1.2
    - r-mass # [not win]
    - r-cluster # [not win]
    - r-lattice # [not win]
    - r-mgcv # [not win]
    - r-permute >=0.7_8

  run:
    - r ==3.1.2
    - r-mass # [not win]
    - r-cluster # [not win]
    - r-lattice # [not win]
    - r-mgcv # [not win]
    - r-permute >=0.7_8

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('vegan')" # [not win]
    - "\"%R%\" -e \"library('vegan')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: !!python/unicode 'http://cran.r-project.org, https://github.com/vegandevs/vegan'

  license: GPL-2
  summary: !!python/unicode 'Ordination methods, diversity analysis and other functions for community
    and vegetation ecologists.'


# The original CRAN metadata for this package was:

# Package: vegan
# Title: Community Ecology Package
# Version: 2.3-0
# Date: 2015-05-21
# Author: Jari Oksanen, F. Guillaume Blanchet, Roeland Kindt, Pierre Legendre,  Peter R. Minchin, R. B. O'Hara, Gavin L. Simpson, Peter Solymos,  M. Henry H. Stevens, Helene Wagner
# Maintainer: Jari Oksanen <jari.oksanen@oulu.fi>
# Depends: permute (>= 0.7-8), lattice, R (>= 2.15.0)
# Suggests: parallel, tcltk
# Imports: MASS, cluster, mgcv
# Description: Ordination methods, diversity analysis and other functions for community and vegetation ecologists.
# License: GPL-2
# BugReports: https://github.com/vegandevs/vegan/issues
# URL: http://cran.r-project.org, https://github.com/vegandevs/vegan
# NeedsCompilation: yes
# Packaged: 2015-05-26 13:00:30 UTC; jarioksa
# Repository: CRAN
# Date/Publication: 2015-05-26 15:48:55

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
