package:
  name: ffmpeg
  version: 2.8.6

source:
  fn: ffmpeg-release-64bit-static.tar.xz
  url: http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz
  md5: 78584e8e5dbfc4ff801bcdda689fd216

build:
  number: 0

requirements:
  build:

  run:

test:
  commands:
    - ffmpeg -version > /dev/null

about:
  home: https://www.ffmpeg.org
  license: GPL
  summary: 'A complete, cross-platform solution to record, convert and stream audio and video.'
