{% set version = '0.2.38' %}

package:
  name: r-mashr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mashr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mashr/mashr_{{ version }}.tar.gz
  sha256: 28ceb8dbd175990c68013c19059a7e73f16ca26f1bf1b38bc815e11ef9bc31f0

build:
  number: 0
  skip: True  # [osx]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake 
    - pkg-config
    - make
  host:
    - r-base
    - r-rcpp >=0.12.11
    - r-rcpparmadillo
    - r-rcppgsl
    - r-abind
    - r-ashr >=2.2_22
    - r-assertthat
    - r-mvtnorm
    - r-plyr
    - r-rmeta
    - openmp
    - openblas
  run:
    - r-base
    - r-rcpp >=0.12.11
    - r-rcpparmadillo
    - r-rcppgsl
    - r-abind
    - r-ashr >=2.2_22
    - r-assertthat
    - r-mvtnorm
    - r-plyr
    - r-rmeta
    - openmp
    - openblas

test:
  commands:
    - $R -e "library('mashr')" 

about:
  home: http://github.com/stephenslab/mashr
  license: BSD-3-Clause
  summary: "An R package for multivariate adaptive shrinkage."
  license_family: BSD
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause'
    - LICENSE
  doc_url: https://stephenslab.github.io/mashr/
  dev_url: https://github.com/stephenslab/mashr

extra:
  identifiers:
    - doi:10.1038/s41588-018-0268-8
