package:
  name: usearch [linux64]
  version: 5.2.236

source:
  fn: usearch5.2.236_i86linux32
  url: file:////util/src/usearch/usearch5.2.236_i86linux32
  md5: 54d26103b4cb44f2d4ceef9d08e4fcac

build:
  number: 0

test:
  commands:
     - usearch -version

about:
  home: http://www.drive5.com/usearch
  license: Custom

# vim:set ts=8 sw=2 
