package:
  name: cd-hit [linux64]
  version: 3.1.1

source:
  fn: cd-hit-2007-0131.tar.gz
  url: http://www.bioinformatics.org/download/cd-hit/cd-hit-2007-0131.tar.gz
  md5: d061c5aae7ed71310282ca578eb6d93f

build:
  number: 0

about:
  home: http://bioinformatics.org/cd-hit/
  license: Free Access

# vim:set ts=8 sw=2 
