{% set name = "Cenote-Taker2" %}
{% set version = "2020.03.26" %}
{% set revision = "2c64f61a4902c80e7556211dc8320938b33c5082" %}
{% set sha256 = "01e4dc5c8a2653203afeb03dc5e6cd641bc30ee42661e758d96c49dc4b52254f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mtisza1/Cenote-Taker2/archive/{{ revision }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - paths.patch

build:
  number: 0
  noarch: generic

requirements:
  run:
    - python=3.6
    - prodigal=2.6.3
    - bwa=0.7.17
    - samtools=1.3
    - mummer=3.23
    - circlator=1.5.5
    - blast=2.9.0
    - bioawk=1.0
    - entrez-direct=13.3
    - krona=2.7.1
    - hmmer=3.3
    - bowtie2=2.3.5
    - trnascan-se=2.0.5
    - bbmap=37.62
    - tbl2asn=25.7
    - emboss=6.6.0
    - numpy=1.18.1
    - pandas=1.0.0
    - matplotlib-base=3.1.3
    - hhsuite=3.2.0
    - last=1047
    - phanotate=2019.08.09
    - perl
    - coreutils

test:
  commands:
    - run_cenote-taker2.0.1.py -h

about:
  home: https://github.com/mtisza1/Cenote-Taker2
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Cenote-Taker2 is a pipeline for divergent virus discovery and annotation."
  dev_url: https://github.com/mtisza1/Cenote-Taker2
