package:
  name: r-mxnet
  version: "0.9.3a"

source:
  git_url: https://github.com/dmlc/mxnet
  git_rev: v0.9.3a
  patches:
    - config.mk.patch

build:
  number: 0

requirements:
  build:
    - gcc
    - r
    - blas
    - opencv
    - gnu-wget
    - r-devtools
    - r-stringr
    - r-rcpp
    - r-diagrammer
    - r-data.table
    - r-roxygen2
  run:
    - r
    - libgcc
    - opencv
    - blas
    - r-devtools
    - r-stringr
    - r-rcpp
    - r-diagrammer
    - r-data.table

test:
  commands:
    - $R -e "library('mxnet')"

about:
  home: http://mxnet.io/
  license: Apache 2.0
  summary: MXNet is an open-source deep learning framework that allows you to define, train, and deploy deep neural networks on a wide array of devices, from cloud infrastructure to mobile devices.
