package:
  name: pymeteo
  version: "0.5"

source:
  fn: v0.5.tar.gz
  url: https://github.com/cwebster2/pyMeteo/archive/v0.5.tar.gz
  md5: f767d140e749ff7cca7d39a202253571

build:
  number: 0
  skip: True # [py27 or osx or py34]

requirements:
  build:
    - python 

  run:
    - python
    - matplotlib
    - numpy
    - h5py ==2.5.0
    - netcdf4
# https://anaconda.org/spyder-ide
    - pyqt5

test:
  # Python imports
  imports:
    - pymeteo

  files:
    - test.py

about:
  home: https://github.com/cwebster2/pyMeteo
  license: Custom OSS
  license_file: LICENSE
  summary: 'General meteorological routines, skew-T/log-p plotting and working with CM1 model data.'
