{% set pkgname = "mro" %}
{% set version = "3.5.3" %}
{% set sha256 = "5e36748a79b930da6befe8827050e9cdd36722d6a8d92e21e3b752bb6afe26bd" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  url: https://mran.blob.core.windows.net/install/mro/{{ version }}/rhel/microsoft-r-open-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: True  # [osx]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - pango
    - fontconfig
    - cairo
    - expat
    - bzip2
    - zlib
    - xorg-libx11
    - xorg-libice
    - xorg-libsm
    - xorg-libxau
    - xorg-libxext
    - xorg-libxft
    - xorg-libxrender
    - xorg-libxt
    - xorg-libxcb

  run:
    - pango
    - fontconfig
    - cairo
    - expat
    - bzip2
    - zlib
    - xorg-libx11
    - xorg-libice
    - xorg-libsm
    - xorg-libxau
    - xorg-libxext
    - xorg-libxft
    - xorg-libxrender
    - xorg-libxt
    - xorg-libxcb
    - ncurses=5.9

test:
  commands:
    - R --version
    - Rscript --version

about:
  home: https://mran.microsoft.com/open
  license: GPLv2
  license_family: GPL
  license_file: MRO_EULA.txt
  summary: "Microsoft R Open is the enhanced distribution of R from Microsoft Corporation."
