{% set version = '1.0.1' %}

package:
  name: r-nistunits
  version: {{ version|replace("-", "_") }}

source:
  fn: NISTunits_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/NISTunits_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/NISTunits/NISTunits_{{ version }}.tar.gz
  sha256: eaccd68db5c73d6a089ce5b323cdd51bc6a6a58ce467987158ba8c9be6a0a94e

build:
  number: 0
  skip: True  # [osx]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('NISTunits')"  # [linux]

about:
  home: https://CRAN.R-project.org/package=NISTunits
  license: GPL (>= 3)
  summary: Fundamental physical constants (Quantity, Value, Uncertainty, Unit) for  SI (International
    System of Units) and non-SI units, plus unit conversions Based on the data from
    NIST (National Institute of Standards and Technology, USA)
  license_family: GPL3
