package:
  name: audioread
  version: !!str 1.0.1

source:
  fn: audioread-1.0.1.tar.gz
  url: https://pypi.python.org/packages/source/a/audioread/audioread-1.0.1.tar.gz
  md5: 2073c69e218b6985c7853aa9cc580877

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - audioread

about:
  home: https://github.com/sampsyo/audioread
  license: MIT
  summary: cross-library (GStreamer + Core Audio + MAD + FFmpeg) audio decoding for Python
