package:
  name: htseq
  version: !!str 0.5.4p5

source:
  fn: HTSeq-0.5.4p5.tar.gz
  url: https://pypi.python.org/packages/source/H/HTSeq/HTSeq-0.5.4p5.tar.gz
  md5: b6d7d5c412bf067e6c33ee1550d99a52
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - htseq = htseq:main
    #
    # Would create an entry point called htseq that calls htseq.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - setuptools
    - matplotlib

test:
  # Python imports
  imports:
    - HTSeq._HTSeq_internal
    - HTSeq.StepVector
    - HTSeq._version
    - HTSeq.scripts.qa
    - HTSeq.scripts.count


  commands:
    - htseq-count -h
    - htseq-qa -h
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www-huber.embl.de/users/anders/HTSeq/
  license:  GNU General Public License (GPL)
  summary: 'A framework to process and analyze data from high-throughput sequencing (HTS) assays'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
