{% set name = "r-depmixs4" %}
{% set version = "1.3.3" %}
{% set sha256 = "62428236e818e1d665ad08eafe088ea89618f0f36a28c20932cd7f98ca064353" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cran.r-project.org/src/contrib/Archive/depmixS4/depmixS4_1.3-3.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True # [osx]
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - r >=3.0.1
    - r-nnet
    - r-mass
    - r-rsolnp
  run:
    - r >=3.0.1
    - r-nnet
    - r-mass
    - r-rsolnp

test:
  commands:
    - $R -e "library('depmixS4')"

about:
  home: http://depmix.r-forge.r-project.org/
  license: GPL (>= 2)
  summary: Fits latent (hidden) Markov models on mixed categorical and continuous (time series) data, otherwise known as dependent mixture models.
  license_family: GPL2
