astor:
  - 0.6.*
gast:
  - 0.2.*
six:
  - 1.10.*
protobuf:
  - 3.4.*
setuptools:
  - 39.1.*
tensorboard:
  - 1.10.*
termcolor:
  - 1.1.*

pin_run_as_build:
  astor:
    lower_bound='0.6.0'
  gast:
    lower_bound='0.2.0'
  six:
    lower_bound='1.10.0'
  protobuf:
    lower_bound='3.6.0'
  setuptools:
    upper_bound='39.1.0'
  tensorboard:
    lower_bound='1.10.0'
    upper_bound='1.11.0'
  termcolor:
    lower_bound='1.1.0'

