{% set name = "tensorflow" %}
{% set version = "1.9.0" %}
{% set sha256 = "ffc3151b06823d57b4a408261ba8efe53601563dfe93af0866751d4f6ca5068c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
    url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz
    sha256:  {{ sha256 }}
    patches:
        - tf_bzl.patch

build:
    number: 0
    skip: True # [osx]

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - bazel 0.11.1

    host:
        - python
        - setuptools
        - numpy >=1.13.3
        - protobuf
        - futures # [py2k]
        - six
        - tensorboard
        - absl-py >=0.1.6
        - backports.weakref # [py < 34]
        - enum34 # [py < 34]
        - wheel # [py3k]
        - mock # [py2k]
        - astor
        - gast
        - termcolor
        - grpcio

    run:
        - python
        - setuptools
        - numpy >=1.13.3
        - protobuf
        - futures # [py2k]
        - six
        - tensorboard
        - absl-py >=0.1.6
        - backports.weakref # [py < 34]
        - enum34 # [py < 34]
        - wheel # [py3k]
        - mock # [py2k]
        - astor
        - gast
        - termcolor
        - grpcio

test:
    imports:
        - tensorflow

about:
    home: https://www.tensorflow.org
    license: Apache 2.0
    license_file: LICENSE
    summary: Computation using data flow graphs for scalable machine learning.

extra:
    skip-lints:
        - in_other_channels
        - uses_git_url
        - missing_hash
        - should_use_compilers
