package:
  name: ea-utils
  version: 1.1.2.537

source:
  fn: ea-utils.1.1.2-537.tar.gz
  url: https://ea-utils.googlecode.com/files/ea-utils.1.1.2-537.tar.gz
  sha1: 688bddb1891ed186be0070d0d581816a35f7eb4e


requirements:
  build:
    - gsl

test:
  commands:
    - fastq-stats -h


about:
  home: https://code.google.com/p/ea-utils/
  license: MIT

