package:
  name: emperor
  version: "0.9.51"

source:
  fn: emperor-0.9.51.tar.gz
  url: https://pypi.python.org/packages/source/e/emperor/emperor-0.9.51.tar.gz
  md5: 9b763cae89fe7b938b8acab4b39b92ba
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - emperor = emperor:main
    #
    # Would create an entry point called emperor that calls emperor.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy >=1.7
    - qcli
    - scikit-bio >=0.2.1,<0.3.0

  run:
    - python
    - numpy >=1.7
    - qcli
    - scikit-bio >=0.2.1,<0.3.0

test:
  # Python imports
  imports:
    - emperor
    - emperor.qiime_backports

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/biocore/emperor
  license: BSD License
  summary: 'Emperor'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
