{% set name = "gpm" %}
{% set version = "1.20.7" %}
{% set sha256 = "fa199e5c7745506df32ebe84d5454385cd6b82cc5036e9247763e41eb4983259" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/telmich/gpm/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libtool
    - autoconf
    - automake
    - bison
    - texinfo
  host:
    - ncurses
  run:
    - ncurses

test:
  commands:
    - gpm -v

about:
  home: https://nico.schottelius.org/software/gpm
  dev_url: https://github.com/telmich/gpm
  summary: 'GPM ("General Purpose Mouse") software provides support for mouse devices in Linux virtual consoles.'
  license: GPLv2
  license_family: GPL
  license_file: COPYING
