{% set name = "matlab-kernel" %}
{% set version = "0.16.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name | replace("-", "_") }}/{{ name | replace("-", "_") }}-{{ version }}.tar.gz
  sha256: b16890c0c12dbf6e3a5ab961058f50ffee85c246ec60fff86aecc3331debfa29

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - ipython >=4.0.0
    - jupyter_client >=4.4.0
    - metakernel >=0.23.0
    - pip
    - python >=3
    - wurlitzer >=1.0.2
  run:
    - ipython >=4.0.0
    - jupyter_client >=4.4.0
    - metakernel >=0.23.0
    - python >=3
    - wurlitzer >=1.0.2

test:
  imports:
    - matlab_kernel

about:
  home: https://github.com/Calysto/matlab_kernel
  license: BSD
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: Jupyter Kernel for Matlab
