{% set name = "lftp" %}
{% set version = "4.8.3" %}
{% set sha256 = "cfbbbd067c25ff9d629828a010cc700214859b02e33b2405dfe7ed045d080f0f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://lftp.yar.ru/ftp/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - gcc # [linux]
    - llvm # [osx]
    - pkgconfig
    - readline {{ CONDA_READLINE }}*
    - ncurses {{ CONDA_NCURSES }}*
    - zlib {{ CONDA_ZLIB }}*
    - openssl
    - bison
    - expat
    - libiconv

  run:
    - libgcc # [linux]
    - readline {{ CONDA_READLINE }}*
    - ncurses  {{ CONDA_NCURSES}}*
    - zlib {{ CONDA_ZLIB }}*
    - openssl
    - expat
    - libiconv

test:
  commands:
    - lftp --help

about:
  home: http://lftp.yar.ru
  license: GPLv3
  license_file: COPYING
  summary: 'LFTP is a sophisticated file transfer program supporting a number of network protocols (ftp, http, sftp, fish, torrent).'
  license_family: BSD
