{% set name = "dm-sonnet-gpu" %}
{% set version = "1.23" %}
{% set sha256 = "73c0046681488b3000f8af5e8fdfc4363a12babef6246306c669d74b538152a3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
    url: https://github.com/deepmind/sonnet/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 1
    skip: True # [osx]

requirements:
    build:
        - gcc # [linux]
        - llvm # [osx]
        - python
        - wheel
        - tensorflow-gpu
        - bazel >=0.4.5
        - absl-py

    run:
        - libgcc # [linux]
        - python
        - tensorflow-gpu
        - six
        - absl-py

test:
    imports:
        - sonnet
    requires:
        - cuda_driver

about:
    home: https://deepmind.github.io/sonnet
    license: Apache 2.0
    license_file: LICENSE
    summary: Sonnet is a library built on top of TensorFlow for building complex neural networks.

extra:
  skip-lints:
    - should_use_compilers
