{% set prefix = "octave" %}
{% set name = "image" %}
{% set version = "2.6.1" %}
{% set sha256 = "a576761094c88b4ea44a977fcdcf47ebc73ed5026cd1180d9884d86d1e89778d" %}

package:
  name: {{ prefix }}-{{ name }}
  version: {{ version }}

source:
  url: https://octave.sourceforge.io/download.php?package={{ name }}-{{ version }}.tar.gz
  folder: {{ name }}-{{ version }}
  sha256: {{ sha256 }}

build:
  number: 2
  skip: True # [osx]
  script:
    - tar -czf {{ name }}-{{ version }}.tar.gz {{ name }}-{{ version }}
    - octave -W -H --eval "pkg install -verbose {{ name }}-{{ version }}.tar.gz"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - octave
  run:
    - octave

test:
  commands:
    - octave -W -H --eval 'pkg load {{ name }}'

about:
  home: https://octave.sourceforge.io/{{ name }}/index.html
  license: GPLv3
  license_family: GPL
  license_file: {{ name }}-{{ version }}/COPYING
  doc_url: https://octave.sourceforge.io/{{ name }}/overview.html
  summary: 'The Octave-forge Image package provides functions for processing images.'
