package:
  name: clearcut [linux64]
  version: 1.0.9

source:
  fn: Clearcut.source.zip
  url: http://www.mothur.org/w/images/9/91/Clearcut.source.zip
  md5: c7c01922d75d5bb6e218d7a9adc72978

build:
  number: 0

test:
  commands:
     - clearcut -V

about:
  home: http://www.mothur.org
  license: Custom

# vim:set ts=8 sw=2 
