package:
  name: pyresample
  version: "1.1.6"

source:
  fn: pyresample-1.1.6.tar.gz
  url: https://pypi.python.org/packages/source/p/pyresample/pyresample-1.1.6.tar.gz
  md5: 1f1b0cbf8a104b082ee742418d0bb07a

build:
  number: 1
  skip: True # [osx]

requirements:
  build:
    - python
    - setuptools
    - pyproj
    - numpy x.x
    - configobj

  run:
    - python
    - pyproj
    - numpy x.x
    - configobj
    - scipy

test:
  # Python imports
  imports:
    - pyresample

about:
  home: https://pyresample.readthedocs.io/en/latest
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  summary: 'Resampling of remote sensing data in Python'
