package:
  name: jbio
  version: 0.1

source:
  git_url: https://github.com/jgurtowski/jbio.git
  git_rev: 0c8b65255b123f79411d278bc45688aacd182941

build:
  number: 0
  skip: True # [py3k]
  skip: True # [osx]

requirements:
  build:
    - python
  run:
    - python

test:
  # Python imports
  imports:
    - jbio

about:
  home: https://github.com/jgurtowski/jbio
  license: GPL-2.0
  summary: General library and tools
