package:
  name: ant
  version: 1.9.6

source:
  fn: apache-ant-1.9.6-bin.tar.gz
  url: https://www.apache.org/dist/ant/binaries/apache-ant-1.9.6-bin.tar.gz
  md5: f1d2e99df927a141c355210d55fe4d32
 
build:
  number: 0
  skip: True # [osx]

requirements:
  run:
    - jdk

test:
  commands:
     - ant -version

about:
  home: http://ant.apache.org
  license: Apache 2.0

# vim:set ts=8 sw=2 
