{% set name = "staphb-toolkit" %}
{% set version = "20200304" %}
{% set sha256 = "2a494d542ebbf36f32fb91a7b8f601ce33b2d94668eb4595cb2fe455e32901b0" %}
{% set commit = "43e800340b87adcc0e624acf74a0ebaec6c0e282" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  # we're using our modified version that supports a proper install, etc.
  url: https://github.com/unlhcc/staphb_toolkit/archive/{{ commit }}.zip
  sha256: {{ sha256 }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - docker-py >=4.1.0
    - spython >=0.0.73
    - psutil >=5.6.3
  run:
    - python >=3.7
    - docker-py >=4.1.0
    - spython >=0.0.73
    - psutil >=5.6.3

test:
  commands:
    - staphb_toolkit | grep "Singularity"

about:
  home: https://staph-b.github.io/staphb_toolkit/
  dev_url: https://github.com/StaPH-B/staphb_toolkit/
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: "Python Toolkit for using containerized programs in either Singularity or Docker"
  description: "The StaPH-B ToolKit is a Python library of commonly used bioinformatics tools that help to inform public health action. The StaPH-B ToolKit utilizes the StaPH-B Docker Images to enable easy access of open-source software without the need of local installation and/or dependency maintenance."
