about:
  home: http://github.com/brentp/pyfasta/
  license:  MIT
  summary: 'fast, memory-efficient, pythonic (and command-line) access to fasta sequence files'

build:
  number: 1
  skip: True # [py3k or osx]

package:
  name: pyfasta
  version: 0.5.2

requirements:
  build:
  - python
  - numpy
  - gcc
  run:
  - python
  - numpy
  - libgcc
  - libgfortran 1.0*

source:
  fn: pyfasta-0.5.2.tar.gz
  md5: bf61ab997dca329675c3eb2ee7cdfcf2
  url: https://pypi.python.org/packages/source/p/pyfasta/pyfasta-0.5.2.tar.gz

test:
  commands:
    - pyfasta -h


