package:
  name: bioconductor-metagenomeseq
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.10.0"

source:
  fn: metagenomeSeq_1.10.0.tar.gz
  url: http://master.bioconductor.org/packages/release/bioc/src/contrib/metagenomeSeq_1.10.0.tar.gz

build:
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r ==3.1.2
    - r-rcolorbrewer
    - r-matrixstats
    - r-gplots
    - bioconductor-biobase
    - bioconductor-limma

  run:
    - r ==3.1.2
    - r-rcolorbrewer
    - r-matrixstats
    - r-gplots
    - bioconductor-biobase
    - bioconductor-limma
test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('metagenomeSeq')" # [not win]

about:
  home: http://www.bioconductor.org/packages/release/bioc/html/metagenomeSeq.html
  license: Artistic-2.0
  summary: Statistical analysis for sparse high-throughput sequencing.
