package:
  name: r-batchjobs
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.6"

source:
  fn: BatchJobs_1.6.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/BatchJobs_1.6.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/BatchJobs/BatchJobs_1.6.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS, testthat
requirements:
  build:
    - r ==3.1.2
    - r-bbmisc >=1.9
    - r-dbi
    - r-rsqlite >=1.0.0
    - r-brew
    - r-checkmate >=1.5.1
    - r-digest
    - r-fail >=1.2
    - r-sendmailr
    - r-stringr

  run:
    - r ==3.1.2
    - r-bbmisc >=1.9
    - r-dbi
    - r-rsqlite >=1.0.0
    - r-brew
    - r-checkmate >=1.5.1
    - r-digest
    - r-fail >=1.2
    - r-sendmailr
    - r-stringr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('BatchJobs')" # [not win]
    - "\"%R%\" -e \"library('BatchJobs')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: !!python/unicode 'https://github.com/tudo-r/BatchJobs'

  license: BSD_2_clause + file LICENSE
  summary: !!python/unicode 'Provides Map, Reduce and Filter variants to generate jobs on batch
    computing systems like PBS/Torque, LSF, SLURM and Sun Grid Engine. Multicore and
    SSH systems are also supported. For further details see the project web page.'


# The original CRAN metadata for this package was:

# Package: BatchJobs
# Title: Batch Computing with R
# Description: Provides Map, Reduce and Filter variants to generate jobs on batch computing systems like PBS/Torque, LSF, SLURM and Sun Grid Engine. Multicore and SSH systems are also supported. For further details see the project web page.
# Author: Bernd Bischl <bernd_bischl@gmx.net>, Michel Lang <michellang@gmail.com>, Henrik Bengtsson <henrikb@braju.com>
# Maintainer: Bernd Bischl <bernd_bischl@gmx.net>
# URL: https://github.com/tudo-r/BatchJobs
# BugReports: https://github.com/tudo-r/BatchJobs/issues
# MailingList: batchjobs@googlegroups.com
# License: BSD_2_clause + file LICENSE
# Depends: R (>= 2.15.0), BBmisc (>= 1.9), methods
# Imports: brew, checkmate (>= 1.5.1), DBI, digest, fail (>= 1.2), parallel, RSQLite (>= 1.0.0), sendmailR, stats, stringr, utils
# Suggests: MASS, testthat
# LazyData: yes
# ByteCompile: yes
# Version: 1.6
# Packaged: 2015-03-18 16:40:05 UTC; bischl
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2015-03-18 18:01:21

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
