package:
  name: r-fail
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.2"

source:
  fn: fail_1.2.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/fail_1.2.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/fail/fail_1.2.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:
    - r ==3.1.2
    - r-bbmisc

  run:
    - r ==3.1.2
    - r-bbmisc

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('fail')" # [not win]
    - "\"%R%\" -e \"library('fail')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: !!python/unicode 'https://github.com/mllg/fail'

  license: BSD_3_clause + file LICENSE
  summary: !!python/unicode 'More comfortable interface to work with a directory of R data or
    source files'


# The original CRAN metadata for this package was:

# Package: fail
# Type: Package
# Title: File Abstraction Interface Layer (FAIL) mimicking a key-value store
# Description: More comfortable interface to work with a directory of R data or source files
# Version: 1.2
# Author: Michel Lang <michellang@gmail.com>
# Maintainer: Michel Lang <michellang@gmail.com>
# URL: https://github.com/mllg/fail
# License: BSD_3_clause + file LICENSE
# Imports: BBmisc
# Suggests: testthat
# ByteCompile: yes
# Collate: 'helper.R' 'methods.R' 'zzz.R' 'cache.R' 'fail.R' 'worker.R' 'sail.R' 'backends.R' 'constructor.R'
# Packaged: 2013-09-19 11:29:30 UTC; lang
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2013-09-19 14:12:29

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
