{% set pkgname = "mro" %}
{% set version = "3.4.4" %}
{% set sha256 = "bf13b714f2d3fe803239bcb96f5fc514e04d50c561ce097f9ba198c872b5a87d" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  fn: microsoft-r-open-{{ version }}.tar.gz
  url: https://mran.blob.core.windows.net/install/mro/{{ version }}/microsoft-r-open-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [osx]

  rpaths:
    - lib/R/lib/
    - lib/
    - lib/lib64/R/lib

requirements:
  build:

  run:
    - libpng
    - pango
    - fontconfig
    - cairo
    - expat
    - bzip2 {{ CONDA_BZIP2 }}*
    - zlib {{ CONDA_ZLIB }}*
    - xorg-libx11
    - xorg-libice
    - xorg-libsm
    - xorg-libxau
    - xorg-libxext
    - xorg-libxft
    - xorg-libxrender
    - xorg-libxt
    - xorg-libxcb

test:
  commands:
    - R --version
    - Rscript --version

about:
  home: https://mran.microsoft.com/open
  license: GPLv2
  license_family: GPL
  license_file: MRO_EULA.txt
  summary: "Microsoft R Open is the enhanced distribution of R from Microsoft Corporation."
