{% set pkgname = "mro" %}
{% set version = "3.4.4" %}
{% set sha256 = "7baf891830a73616eda4f6b3035204ceb6218ab0e085aca9b4d74558712bf0d6" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  url: https://mran.blob.core.windows.net/install/mro/{{ version }}/microsoft-r-open-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [osx]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - libpng
    - pango
    - fontconfig
    - cairo
    - expat
    - bzip2
    - zlib
    - xorg-libx11
    - xorg-libice
    - xorg-libsm
    - xorg-libxau
    - xorg-libxext
    - xorg-libxft
    - xorg-libxrender
    - xorg-libxt
    - xorg-libxcb

  run:
    - libpng
    - pango
    - fontconfig
    - cairo
    - expat
    - bzip2
    - zlib
    - xorg-libx11
    - xorg-libice
    - xorg-libsm
    - xorg-libxau
    - xorg-libxext
    - xorg-libxft
    - xorg-libxrender
    - xorg-libxt
    - xorg-libxcb

test:
  commands:
    - R --version
    - Rscript --version

about:
  home: https://mran.microsoft.com/open
  license: GPLv2
  license_family: GPL
  license_file: MRO_EULA.txt
  summary: "Microsoft R Open is the enhanced distribution of R from Microsoft Corporation."
