package:
  name: ucsc-tools [linux64]
  version: 320

source:
  fn: ucsc_tools-320.tar.gz
  url: file:////util/src/ucsc_tools/ucsc_tools-320.tar.gz
  md5: a55359262b9451949ee046c78b973f91

build:
  number: 0

about:
  home: http://genome.ucsc.edu
  license: Free for academic, nonprofit, and personal use

# vim:set ts=8 sw=2 
