package:
  name: qiime-default-reference
  version: "0.1.3"

source:
  fn: qiime-default-reference-0.1.3.tar.gz
  url: https://pypi.python.org/packages/source/q/qiime-default-reference/qiime-default-reference-0.1.3.tar.gz
  md5: 4a5ccf5930690478de1eb881e8030bff
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - qiime-default-reference = qiime-default-reference:main
    #
    # Would create an entry point called qiime-default-reference that calls qiime-default-reference.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  # Python imports
  imports:
    - qiime_default_reference
    - qiime_default_reference.gg_13_8_otus
    - qiime_default_reference.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.qiime.org
  license: CC BY-SA 3.0
  summary: 'Default reference data files for use with QIIME.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
