protobuf:
  - 3.4.1
cub:
  - 1.7.2
eigen:
  - 3.3.5
pybind11:
  - 2.2.3
pin_run_as_build:
  protobuf:
    min_pin: x.x
    max_pin: x.x
  cub:
    min_pin: x.x.x
    max_pin: x.x
  eigen:
    min_pin: x.x.x
    max_pin: x.x
  pybind11:
    min_pin: x.x.x
    max_pin: x.x
  cudatoolkit:
    min_pin: x.x.x
    max_pin: x.x
  cudnn:
    min_pin: x.x.x
    max_pin: x.x.x
