{% set xorg_name = "libXScrnSaver" %}
{% set xorg_category = "lib" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.2.2" %}
{% set sha256 = "8ff1efa7341c7f34bcf9b17c89648d6325ddaae22e3904e091794e0b4426ce1d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: True  # [osx]

requirements:
  build:
    - gcc # [linux]
    - pkg-config
    - xorg-libx11 1.6.*
    - xorg-libxext 1.3*
    - xorg-xextproto 7.3*
    - xorg-scrnsaverproto 1.2*
    - xorg-libpthread-stubs

  run:
    - libgcc # [linux]
    - libxcb
    - xorg-libx11 1.6.*
    - xorg-libxext 1.3*
    - xorg-libxdmcp 1.1*

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'X11 Screen Saver extension client library.'
