package:
  name: r-rgexf
  version: "0.15.3"

source:
  fn: rgexf_0.15.3.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/rgexf_0.15.3.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/rgexf/rgexf_0.15.3.tar.gz

build:
  number: 0
  skip: True # [osx]

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r
    - r-rook
    - r-xml
    - r-igraph
    - gcc

  run:
    - libgcc
    - r
    - r-rook
    - r-xml
    - r-igraph

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rgexf')"

about:
  home: http://bitbucket.org/gvegayon/rgexf, http://www.ggvega.com
  license: GPL (>= 3)
  summary: Create, read and write GEXF (Graph Exchange XML Format) graph files (used in Gephi
    and others). Using the XML package, it allows the user to easily build/read graph
    files including attributes, GEXF viz attributes (such as color, size, and position),
    network dynamics (for both edges and nodes) and edge weighting. Users can build/handle
    graphs element-by-element or massively through data-frames, visualize the graph
    on a web browser through "sigmajs" (a javascript library) and interact with the
    igraph package.
  license_family: GPL3
