package:
  name: giflib
  version: 5.1.2

source:
  fn: giflib-5.1.2.tar.gz
  url: http://downloads.sourceforge.net/project/giflib/giflib-5.1.2.tar.gz
  md5: 241a5825d00a36055fcc71874d97cf7b
	
build:
    number: 0
	  
requirements:
  build:
    - gcc

  run:
    - libgcc

test:
  commands:
  - gif2rgb -h > /dev/null 2>&1
  - gifbuild -h > /dev/null 2>&1
  - gifclrmp -h > /dev/null 2>&1
  - gifecho -h > /dev/null 2>&1
  - giffix -h > /dev/null 2>&1
  - gifinto -h > /dev/null 2>&1
  - giftext -h > /dev/null 2>&1

about:
  home: http://giflib.sourceforge.net
  license: Open Source
  license_file: COPYING
  summary: "giflib is a library for reading and writing gif images. It is API and ABI compatible with libungif which was in wide use while the LZW compression algorithm was patented."
