{% set name = "PyEnsembl" %}
{% set version = "1.2.6" %}
{% set sha256 = "28a5b7dcd0c15ba3fbffb2e13120394d0f95f6968cbf6314ec71afebb3d981e7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name|lower }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/23/5b/c6123d2939a80ff47d02ff95744ce61e04cd467180894c805d5f414ad111/{{ name|lower }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - pyensembl = pyensembl.shell:run
  number: 0

requirements:
  build:
    - python
    - setuptools
    - typechecks >=0.0.2
    - numpy >=1.7
    - pandas >=0.15
    - datacache >=0.4.19
    - memoized-property >=1.0.2
    - six >=1.9.0
    - gtfparse >=0.0.3
    - serializable
    - tinytimer
    - nose >=1.3.3
    - pylint >=1.4.4

  run:
    - python
    - typechecks >=0.0.2
    - numpy >=1.7
    - pandas >=0.15
    - datacache >=0.4.19
    - memoized-property >=1.0.2
    - six >=1.9.0
    - gtfparse >=0.0.3
    - serializable
    - tinytimer
    - nose >=1.3.3
    - pylint >=1.4.4

test:
  imports:
    - pyensembl
  commands:
    - pyensembl --help

about:
  home: https://github.com/openvax/pyensembl
  license: Apache Software License
  summary: 'Python interface to ensembl reference genome metadata'
  license_family: APACHE
  license_file: LICENSE
