package:
  name: gmp
  version: 6.1.0

source:
  fn: gmp-6.1.0.tar.bz2
  url: https://gmplib.org/download/gmp/gmp-6.1.0.tar.bz2
  sha1: db38c7b67f8eea9f2e5b8a48d219165b2fdab11f

build:
  number: 0

test:
  files:
    - test.c

about:
  home: http://gmplib.org/
  license: LGPLv3
  summary: GMP is a free library for arbitrary precision arithmetic, operating on signed integers, rational numbers, and floating-point numbers.
