{% set name = "perl-array-intspan" %}
{% set version = "2.003" %}
{% set sha256 = "fb6a6a8972874f84aa3e57c43f693edd9b0170075fb3e06d43c0f748ae53e681" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/D/DD/DDUMONT/Array-IntSpan-2.003.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [osx]

requirements:
  host:
    - perl 5.26
    - perl-extutils-makemaker
    - perl-carp
    - perl-data-dumper
  run:
    - perl 5.26
    - perl-carp

about:
  home: https://github.com/dod38fr/array-intspan-perl
  license: artistic_1
  summary: 'Handles arrays of scalars or objects using integer ranges'
