{% set name = "libgdiplus" %}
{% set version = "6.0.4" %}
{% set sha256 = "9a5e3f98018116f99361520348e9713cd05680c231d689a83d87acfaf237d3a8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/mono/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - configure.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - automake
    - libtool
    - cmake
    - pkg-config
  host:
    - cairo
    - libpng
    - libtiff
    - libexif
    - glib 
    - libjpeg-turbo
    - giflib
    - pango
  run:
    - cairo
    - libpng
    - libtiff
    - libexif
    - glib
    - libjpeg-turbo
    - giflib
    - pango
 
test:
  commands:
    - test -f ${PREFIX}/lib/libgdiplus.dylib # [osx]
    - test -f ${PREFIX}/lib/libgdiplus.so # [linux]
    - test -f ${PREFIX}/lib/libgdiplus.a

about:
  home: https://www.mono-project.com/docs/gui/libgdiplus/
  license: Custom OSS
  license_family: OTHER
  license_file: LICENSE
  summary: "Libgdiplus is the Mono library that provides a GDI+-compatible API on non-Windows operating systems. Our implementation uses Cairo to do most of the heavy lifting."
