package:
  name: sumaclust [linux64]
  version: 1.0.00

source:
  fn: suma_package_V_1.0.00.tar.gz
  url: ftp://ftp.microbio.me/pub/QIIME-v1.9.0-dependencies/suma_package_V_1.0.00.tar.gz
  md5: e528493d05225a605adacd0961b8f50c

build:
  number: 0

test:
  commands:
     - sumaclust -h
     - sumatra -h

about:
  home: http://metabarcoding.org/sumatra
  license: CeCILL FSLA

# vim:set ts=8 sw=2 
