package:
    name: tensorflow
    version: 1.0.0

source:
    fn: v1.0.0.tar.gz
    url: https://github.com/tensorflow/tensorflow/archive/v1.0.0.tar.gz
    md5: c8db48b2054ff5cc24f3bcf9c1b78662
    patches:
        - librt.patch

build:
    number: 0

requirements:
    build:
        - gcc # [not osx]
        - llvm # [osx]
        - python
        - wheel
        - numpy >=1.11.0
        - bazel >=0.4.2
        - protobuf >=3.1.0
        - perl

    run:
        - libgcc # [not osx]
        - python
        - numpy >=1.11.0
        - protobuf >=3.1.0


test:
    imports:
        - tensorflow


about:
    home: https://www.tensorflow.org
    license: Apache 2.0
    license_file: LICENSE
    summary: Computation using data flow graphs for scalable machine learning.
