package:
  name: raxml [linux64]
  version: 7.3.0

source:
  fn: stamatak-standard-RAxML-5_7_2012.tgz
  url: file:///util/src/raxml/dist/stamatak-standard-RAxML-5_7_2012.tgz 
  md5: a9aec96746c26beb3101151ad8c3c869

build:
  number: 0

  features:
    - avx

test:
  commands:
     - raxmlHPC -v

about:
  home: http://sco.h-its.org/exelixis/web/software/raxml/
  license: GPL

# vim:set ts=8 sw=2 
