package:
  name: pyqi
  version: !!str 0.3.2

source:
  fn: pyqi-0.3.2.tar.gz
  url: https://pypi.python.org/packages/source/p/pyqi/pyqi-0.3.2.tar.gz
  md5: 9507c06eeb22a816d963c860ad8e92ae
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyqi = pyqi:main
    #
    # Would create an entry point called pyqi that calls pyqi.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pyqi
    - pyqi.commands
    - pyqi.core
    - pyqi.core.interfaces
    - pyqi.core.interfaces.html
    - pyqi.core.interfaces.optparse
    - pyqi.interfaces
    - pyqi.interfaces.html
    - pyqi.interfaces.html.config
    - pyqi.interfaces.optparse
    - pyqi.interfaces.optparse.config

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://bipy.github.io/pyqi
  license:  BSD License
  summary: 'pyqi: expose your interface'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
