package:
  name: chipathlon
  version: "1.0"

source:
  git_url: https://git.unl.edu/hcc/chipathlon.git
  git_rev: master

build:
  number: 2
  skip: True # [py3k]
  skip: True # [osx]

requirements:
  build:
    - python
    - pymongo
    - pyyaml

  run:
    - python
    - pymongo
    - pyyaml
    - bedtools
    - bwa
    - ccat
    - gem
    - jamm
    - macs2
    - picard
    - samtools
    - bowtie2
#    - idr
    - r
    - r-spp
    - peakranger
#    - bosco
    - pegasus-wms
    - pymysql
    - music
    - pepr
    - hiddendomains
    - zerone
    - phantompeakqualtools
    - requests

test:
  commands:
    - chip-gen --help
    - chip-create-run --help
  imports:
    - chipathlon

about:
  home: "https://git.unl.edu/hcc/chipathlon"
  license: Apache-2.0
  summary: "ChiPAthlon"
