package:
  name: scientificpython
  version: 2.8.1

source:
  fn: ScientificPython-2.8.1.tar.gz
  url: https://sourcesup.renater.fr/frs/download.php/file/4411/ScientificPython-2.8.1.tar.gz
  md5: 73ee0df19c7b58cdf2954261f0763c77

build:
  number: 2
  skip: True #[py3k]
  skip: True # [osx]

requirements:
  build:
    - python
    - libnetcdf 4.4*
    - numpy
    - gcc
    - jpeg ==8d
    - gmp {{CONDA_GMP}}*

  run:
    - python
    - libnetcdf 4.4*
    - numpy
    - libgcc
    - jpeg ==8d
    - gmp {{CONDA_GMP}}*

test:
  # Python imports
  imports:
    - Scientific
    - Scientific.IO
    - Scientific.Clustering
    - Scientific.DistributedComputing
    - Scientific.Functions
    - Scientific.Physics
    - Scientific.Signals
    - Scientific.Threading
    - Scientific.Visualization


about:
  home: http://dirac.cnrs-orleans.fr/ScientificPython/
  license: CeCILL-C FREE SOFTWARE LICENSE AGREEMENT
  summary: 'ScientificPython is a collection of Python modules that are useful for scientific computing.'

