package:
  name: libvpx
  version: 1.5.0

source:
  url: http://storage.googleapis.com/downloads.webmproject.org/releases/webm/libvpx-1.5.0.tar.bz2
  md5: 49e59dd184caa255886683facea56fca

build:
    number: 0
    skip: True # [osx]

requirements:
  build:
    - gcc
    - yasm

  run:
    - libgcc

test:
  commands:
    - test -f ${PREFIX}/lib/libvpx.so
    - test -f ${PREFIX}/lib/libvpx.a
    - test -d ${PREFIX}/include/vpx

about:
  home: http://www.webmproject.org/code/
  license: BSD
  license_file: LICENSE
  summary: "This package, from the WebM project, provides the reference implementations of the VP8 Codec, used in most current html5 video, and of the next-generation VP9 Codec."

extra:
  skip-lints:
    - in_other_channels
    - should_use_compilers
