{% set name = "tensorflow-gpu" %}
{% set version = "1.5.0" %}
{% set sha256 = "0642781c3a3a8c2c4834b91b86aec385f0b2ada7d721571458079478cc5b29c8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
    fn: v{{ version }}.tar.gz
    url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz
    sha256:  {{ sha256 }}
    patches:
        - librt.patch
        - no_android.patch
        - cuda_lib_path.patch
        - cc_flags.patch

build:
    number: 1
    skip: True # [osx]

requirements:
    build:
        - gcc # [linux]
        - llvm # [osx]
        - python
        - wheel
        - numpy x.x
        - bazel ==0.8.0
        - protobuf ==3.4.0
        - perl
        - binutils >=2.22
        - futures ==3.1.1 # [py2k]
        - six >=1.10.0
        - tensorflow-tensorboard >=1.5.0,<1.6.0
        - absl-py >=0.1.6
        - backports.weakref >=1.0rc1 # [py < 34]
        - enum34 >=1.1.6 # [py < 34]
        - wheel # [py3k]
        - mock # [py2k]
        - cuda-driver {{ CONDA_CUDA_DRIVER }}*
        - cudatoolkit {{ CONDA_CUDA_TOOLKIT }}*
        - cudnn {{ CONDA_CUDA_CUDNN }}*

    run:
        - libgcc # [linux]
        - python
        - numpy x.x
        - protobuf >=3.4.0
        - futures ==3.1.1 # [py2k]
        - six >=1.10.0
        - tensorflow-tensorboard >=1.5.0,<1.6.0
        - absl-py >=0.1.6
        - backports.weakref >=1.0rc1 # [py < 34]
        - enum34 >=1.1.6 # [py < 34]
        - wheel # [py3k]
        - mock # [py2k]
        - cuda-driver {{ CONDA_CUDA_DRIVER }}*
        - cudatoolkit {{ CONDA_CUDA_TOOLKIT }}*
        - cudnn {{ CONDA_CUDA_CUDNN }}*

test:
    imports:
        - tensorflow

about:
    home: https://www.tensorflow.org
    license: Apache 2.0
    license_file: LICENSE
    summary: Computation using data flow graphs for scalable machine learning.
