{% set name = "mumax3" %}
{% set version = "3.10" %}
{% set sha256 = "42c858661cec3896685ff4babea11e711f71fd6ea37d20c2bed7e4a918702caa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mumax/3/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  folder: src/github.com/mumax/3

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - cuda_driver
    - go-cgo
  host:
    - cudatoolkit
  run:
    - cudatoolkit
    - gnuplot

test:
  commands:
    - mumax3 -h 2>&1 | grep mumax3 > /dev/null
    - mumax3-convert -h 2>&1 | grep mumax3-convert > /dev/null
    - mumax3-httpfsd -h 2>&1 | grep mumax3-httpfsd > /dev/null
    - mumax3-plot -h 2>&1 | grep mumax3-plot > /dev/null
    - mumax3-script -h 2>&1 | grep mumax3-script > /dev/null
    - mumax3-server -h 2>&1 | grep mumax3-server > /dev/null
  requires:
    - cuda_driver

about:
  home: http://mumax.github.io
  license: GPL3
  license_family: GPL
  license_file: src/github.com/mumax/3/LICENSE
  summary: "GPU-accelerated micromagnetic simulator"
  doc_url: http://mumax.github.io
  dev_url: https://github.com/mumax/3
