package:
  name: bedtools [linux64]
  version: 2.19.1

source:
  fn: v2.19.1.tar.gz
  url: https://github.com/arq5x/bedtools2/archive/v2.19.1.tar.gz
  md5: 98c549049c44ce39d58e63e152b99566

build:
  number: 0

test:
  commands:
     - bedtools --version

about:
  home: http://bedtools.readthedocs.org 
  license: GPLv2

# vim:set ts=8 sw=2 
